resource "aws_vpc" "this" {}
resource "aws_subnet" "public" {}
resource "aws_subnet" "app" {}
resource "aws_subnet" "data" {}
resource "aws_route_table" "public" {}
resource "aws_route_table" "app" {}
resource "aws_route_table" "data" {}
resource "aws_vpc_endpoint" "gateway" {}
resource "aws_flow_log" "this" {}
resource "aws_security_group" "resolver_inbound" {}
