       IDENTIFICATION DIVISION.
       PROGRAM-ID. atm-release-router.
       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
           SELECT HOLD-FILE ASSIGN TO "/app/data/holds.psv" ORGANIZATION IS LINE SEQUENTIAL.
           SELECT REL-FILE ASSIGN TO "/app/data/releases.psv" ORGANIZATION IS LINE SEQUENTIAL.
           SELECT REP-FILE ASSIGN TO "/app/out/release_report.csv" ORGANIZATION IS LINE SEQUENTIAL.
           SELECT SUM-FILE ASSIGN TO "/app/out/release_summary.txt" ORGANIZATION IS LINE SEQUENTIAL.
       DATA DIVISION.
       FILE SECTION.
       FD HOLD-FILE. 01 HOLD-LINE PIC X(300).
       FD REL-FILE. 01 REL-LINE PIC X(300).
       FD REP-FILE. 01 REP-LINE PIC X(300).
       FD SUM-FILE. 01 SUM-LINE PIC X(120).
       WORKING-STORAGE SECTION.
       01 EOF-H PIC X VALUE "N".
       01 EOF-R PIC X VALUE "N".
       01 H-COUNT PIC 9(4) VALUE 0.
       01 I PIC 9(4) VALUE 0.
       01 MATCH-IDX PIC 9(4) VALUE 0.
       01 MATCHED-FLAG PIC X VALUE "N".
       01 MATCHED-COUNT PIC 9(8) VALUE 0.
       01 UNMATCHED-COUNT PIC 9(8) VALUE 0.
       01 MATCHED-AMOUNT PIC 9(12) VALUE 0.
       01 UNMATCHED-AMOUNT PIC 9(12) VALUE 0.
       01 WORK-AMT PIC 9(10) VALUE 0.
       01 REL-ID PIC X(30).
       01 REL-HOLD PIC X(30).
       01 REL-CARD PIC X(30).
       01 REL-TERM PIC X(30).
       01 REL-CHAN PIC X(30).
       01 REL-AMT PIC X(20).
       01 REL-TS PIC X(20).
       01 REL-REASON PIC X(30).
       01 REL-REGION PIC X(30).
       01 HOLD-TABLE.
          05 H-ROW OCCURS 200 TIMES.
             10 H-ID PIC X(30).
             10 H-CARD PIC X(30).
             10 H-TERM PIC X(30).
             10 H-CHAN PIC X(30).
             10 H-AMT PIC X(20).
             10 H-TS PIC X(20).
             10 H-STATUS PIC X(30).
             10 H-REGION PIC X(30).
             10 H-USED PIC X.
       PROCEDURE DIVISION.
       MAIN-PARA.
           CALL "SYSTEM" USING "mkdir -p /app/out"
           PERFORM LOAD-HOLDS
           OPEN INPUT REL-FILE
           OPEN OUTPUT REP-FILE SUM-FILE
           MOVE "release_id,hold_id,card_id,terminal_id,channel,amount_cents,reason,status" TO REP-LINE
           WRITE REP-LINE
           READ REL-FILE AT END MOVE "Y" TO EOF-R END-READ
           PERFORM UNTIL EOF-R = "Y"
               READ REL-FILE
                   AT END MOVE "Y" TO EOF-R
                   NOT AT END PERFORM PROCESS-REL
               END-READ
           END-PERFORM
           PERFORM WRITE-SUMMARY
           CLOSE REL-FILE REP-FILE SUM-FILE
           STOP RUN.
       LOAD-HOLDS.
           OPEN INPUT HOLD-FILE
           READ HOLD-FILE AT END MOVE "Y" TO EOF-H END-READ
           PERFORM UNTIL EOF-H = "Y"
               READ HOLD-FILE
                   AT END MOVE "Y" TO EOF-H
                   NOT AT END
                       ADD 1 TO H-COUNT
                       UNSTRING HOLD-LINE DELIMITED BY "|" INTO H-ID(H-COUNT) H-CARD(H-COUNT) H-TERM(H-COUNT) H-CHAN(H-COUNT) H-AMT(H-COUNT) H-TS(H-COUNT) H-STATUS(H-COUNT) H-REGION(H-COUNT)
                       MOVE "N" TO H-USED(H-COUNT)
               END-READ
           END-PERFORM
           CLOSE HOLD-FILE.
       PROCESS-REL.
           UNSTRING REL-LINE DELIMITED BY "|" INTO REL-ID REL-HOLD REL-CARD REL-TERM REL-CHAN REL-AMT REL-TS REL-REASON REL-REGION
           MOVE "N" TO MATCHED-FLAG
           MOVE 0 TO MATCH-IDX
           PERFORM VARYING I FROM 1 BY 1 UNTIL I > H-COUNT OR MATCHED-FLAG = "Y"
               IF REL-HOLD = H-ID(I) AND REL-AMT = H-AMT(I)
                   MOVE "Y" TO MATCHED-FLAG
                   MOVE I TO MATCH-IDX
               END-IF
           END-PERFORM
           MOVE REL-AMT TO WORK-AMT
           IF MATCHED-FLAG = "Y"
               ADD 1 TO MATCHED-COUNT
               ADD WORK-AMT TO MATCHED-AMOUNT
               STRING REL-ID DELIMITED BY SPACE "," REL-HOLD DELIMITED BY SPACE "," REL-CARD DELIMITED BY SPACE "," REL-TERM DELIMITED BY SPACE "," H-CHAN(MATCH-IDX) DELIMITED BY SPACE "," REL-AMT DELIMITED BY SPACE "," REL-REASON DELIMITED BY SPACE ",MATCHED" DELIMITED BY SIZE INTO REP-LINE END-STRING
           ELSE
               ADD 1 TO UNMATCHED-COUNT
               ADD WORK-AMT TO UNMATCHED-AMOUNT
               STRING REL-ID DELIMITED BY SPACE "," REL-HOLD DELIMITED BY SPACE "," REL-CARD DELIMITED BY SPACE "," REL-TERM DELIMITED BY SPACE ",," REL-AMT DELIMITED BY SPACE "," REL-REASON DELIMITED BY SPACE ",UNMATCHED" DELIMITED BY SIZE INTO REP-LINE END-STRING
           END-IF
           WRITE REP-LINE.
       WRITE-SUMMARY.
           STRING "matched_count=" MATCHED-COUNT DELIMITED BY SIZE INTO SUM-LINE END-STRING
           WRITE SUM-LINE
           STRING "matched_amount_cents=" MATCHED-AMOUNT DELIMITED BY SIZE INTO SUM-LINE END-STRING
           WRITE SUM-LINE
           STRING "unmatched_count=" UNMATCHED-COUNT DELIMITED BY SIZE INTO SUM-LINE END-STRING
           WRITE SUM-LINE
           STRING "unmatched_amount_cents=" UNMATCHED-AMOUNT DELIMITED BY SIZE INTO SUM-LINE END-STRING
           WRITE SUM-LINE.