       >>SOURCE FORMAT FREE
IDENTIFICATION DIVISION.
PROGRAM-ID. LOCKBOX-APPLY.

ENVIRONMENT DIVISION.
INPUT-OUTPUT SECTION.
FILE-CONTROL.
    SELECT INVOICE-FILE ASSIGN TO "/app/data/invoices.dat"
        ORGANIZATION IS LINE SEQUENTIAL.
    SELECT PAYMENT-FILE ASSIGN TO "/app/data/payments.dat"
        ORGANIZATION IS LINE SEQUENTIAL.
    SELECT REPORT-FILE ASSIGN TO "/app/out/lockbox_report.csv"
        ORGANIZATION IS LINE SEQUENTIAL.
    SELECT SUMMARY-FILE ASSIGN TO "/app/out/lockbox_summary.txt"
        ORGANIZATION IS LINE SEQUENTIAL.

DATA DIVISION.
FILE SECTION.
FD INVOICE-FILE.
01 INVOICE-REC PIC X(80).

FD PAYMENT-FILE.
01 PAYMENT-REC PIC X(80).

FD REPORT-FILE.
01 REPORT-REC PIC X(160).

FD SUMMARY-FILE.
01 SUMMARY-REC PIC X(80).

WORKING-STORAGE SECTION.
01 EOF-INVOICE PIC X VALUE "N".
01 EOF-PAYMENT PIC X VALUE "N".
01 WS-IDX PIC 9(4) COMP VALUE 0.
01 WS-INVOICE-COUNT PIC 9(4) COMP VALUE 0.
01 WS-MATCH-IDX PIC 9(4) COMP VALUE 0.
01 WS-APPLIED-COUNT PIC 9(6) VALUE 0.
01 WS-UNAPPLIED-COUNT PIC 9(6) VALUE 0.
01 WS-APPLIED-AMOUNT PIC S9(12) SIGN LEADING SEPARATE VALUE 0.
01 WS-UNAPPLIED-AMOUNT PIC 9(12) VALUE 0.
01 WS-PAY-INVOICE PIC X(12).
01 WS-PAY-CUSTOMER PIC X(8).
01 WS-PAY-AMOUNT-TEXT PIC X(10).
01 WS-PAY-AMOUNT PIC 9(10).
01 WS-PAY-DATE PIC X(8).
01 WS-PAY-CHANNEL PIC X(3).
01 WS-PAY-DISPOSITION PIC X.
01 WS-STATUS PIC X(9).

01 INVOICE-TABLE.
   05 INVOICE-ENTRY OCCURS 300 TIMES.
      10 INV-ID PIC X(12).
      10 INV-CUSTOMER PIC X(8).
      10 INV-AMOUNT PIC 9(10).
      10 INV-STATUS PIC X.
      10 INV-CUTOFF-DATE PIC X(8).
      10 INV-CHANNEL PIC X(3).
      10 INV-HOLD PIC X.

PROCEDURE DIVISION.
MAIN.
    PERFORM LOAD-INVOICES.
    PERFORM WRITE-REPORT-HEADER.
    PERFORM PROCESS-PAYMENTS.
    PERFORM WRITE-SUMMARY.
    STOP RUN.

LOAD-INVOICES.
    OPEN INPUT INVOICE-FILE.
    PERFORM UNTIL EOF-INVOICE = "Y"
        READ INVOICE-FILE
            AT END
                MOVE "Y" TO EOF-INVOICE
            NOT AT END
                IF INVOICE-REC(1:1) = "I"
                    ADD 1 TO WS-INVOICE-COUNT
                    MOVE INVOICE-REC(2:12) TO INV-ID(WS-INVOICE-COUNT)
                    MOVE INVOICE-REC(14:8) TO INV-CUSTOMER(WS-INVOICE-COUNT)
                    MOVE INVOICE-REC(22:10) TO INV-AMOUNT(WS-INVOICE-COUNT)
                    MOVE INVOICE-REC(32:1) TO INV-STATUS(WS-INVOICE-COUNT)
                    MOVE INVOICE-REC(33:8) TO INV-CUTOFF-DATE(WS-INVOICE-COUNT)
                    MOVE INVOICE-REC(41:3) TO INV-CHANNEL(WS-INVOICE-COUNT)
                    MOVE INVOICE-REC(44:1) TO INV-HOLD(WS-INVOICE-COUNT)
                END-IF
        END-READ
    END-PERFORM.
    CLOSE INVOICE-FILE.

WRITE-REPORT-HEADER.
    OPEN OUTPUT REPORT-FILE.
    MOVE SPACES TO REPORT-REC.
    MOVE "invoice_id,customer_id,channel,amount_cents,payment_date,status" TO REPORT-REC.
    WRITE REPORT-REC.

PROCESS-PAYMENTS.
    OPEN INPUT PAYMENT-FILE.
    PERFORM UNTIL EOF-PAYMENT = "Y"
        READ PAYMENT-FILE
            AT END
                MOVE "Y" TO EOF-PAYMENT
            NOT AT END
                IF PAYMENT-REC(1:1) = "P"
                    PERFORM PARSE-PAYMENT
                    PERFORM FIND-MATCH
                    IF WS-MATCH-IDX > 0
                        MOVE "APPLIED" TO WS-STATUS
                        ADD 1 TO WS-APPLIED-COUNT
                        SUBTRACT WS-PAY-AMOUNT FROM WS-APPLIED-AMOUNT
                    ELSE
                        MOVE "UNAPPLIED" TO WS-STATUS
                        ADD 1 TO WS-UNAPPLIED-COUNT
                        ADD WS-PAY-AMOUNT TO WS-UNAPPLIED-AMOUNT
                    END-IF
                    PERFORM WRITE-REPORT-ROW
                END-IF
        END-READ
    END-PERFORM.
    CLOSE PAYMENT-FILE.
    CLOSE REPORT-FILE.

PARSE-PAYMENT.
    MOVE PAYMENT-REC(2:12) TO WS-PAY-INVOICE.
    MOVE PAYMENT-REC(14:8) TO WS-PAY-CUSTOMER.
    MOVE PAYMENT-REC(22:10) TO WS-PAY-AMOUNT-TEXT.
    MOVE PAYMENT-REC(22:10) TO WS-PAY-AMOUNT.
    MOVE PAYMENT-REC(32:8) TO WS-PAY-DATE.
    MOVE PAYMENT-REC(40:3) TO WS-PAY-CHANNEL.
    MOVE PAYMENT-REC(43:1) TO WS-PAY-DISPOSITION.

FIND-MATCH.
    MOVE 0 TO WS-MATCH-IDX.
    PERFORM VARYING WS-IDX FROM 1 BY 1
        UNTIL WS-IDX > WS-INVOICE-COUNT OR WS-MATCH-IDX > 0
        IF INV-ID(WS-IDX)(1:10) = WS-PAY-INVOICE(1:10)
            AND INV-CUSTOMER(WS-IDX) = WS-PAY-CUSTOMER
            AND INV-AMOUNT(WS-IDX) = WS-PAY-AMOUNT
            AND INV-STATUS(WS-IDX) NOT = "V"
            AND WS-PAY-DATE < INV-CUTOFF-DATE(WS-IDX)
            AND (INV-CHANNEL(WS-IDX) = "ACH"
                 OR INV-CHANNEL(WS-IDX) = "WIR"
                 OR INV-CHANNEL(WS-IDX) = "CRD")
            AND INV-CHANNEL(WS-IDX) = WS-PAY-CHANNEL
                MOVE WS-IDX TO WS-MATCH-IDX
        END-IF
    END-PERFORM.

WRITE-REPORT-ROW.
    MOVE SPACES TO REPORT-REC.
    IF WS-MATCH-IDX > 0
        STRING
            WS-PAY-INVOICE DELIMITED BY SIZE
            "," DELIMITED BY SIZE
            WS-PAY-CUSTOMER DELIMITED BY SIZE
            "," DELIMITED BY SIZE
            INV-CHANNEL(WS-MATCH-IDX) DELIMITED BY SIZE
            "," DELIMITED BY SIZE
            WS-PAY-AMOUNT-TEXT DELIMITED BY SIZE
            "," DELIMITED BY SIZE
            WS-PAY-DATE DELIMITED BY SIZE
            "," DELIMITED BY SIZE
            WS-STATUS DELIMITED BY SPACE
            INTO REPORT-REC
        END-STRING
    ELSE
        STRING
            WS-PAY-INVOICE DELIMITED BY SIZE
            "," DELIMITED BY SIZE
            WS-PAY-CUSTOMER DELIMITED BY SIZE
            ",," DELIMITED BY SIZE
            WS-PAY-AMOUNT-TEXT DELIMITED BY SIZE
            "," DELIMITED BY SIZE
            WS-PAY-DATE DELIMITED BY SIZE
            ",UNAPPLIED" DELIMITED BY SIZE
            INTO REPORT-REC
        END-STRING
    END-IF.
    WRITE REPORT-REC.

WRITE-SUMMARY.
    OPEN OUTPUT SUMMARY-FILE.
    MOVE SPACES TO SUMMARY-REC.
    STRING "applied_count=" DELIMITED BY SIZE
        WS-APPLIED-COUNT DELIMITED BY SIZE
        INTO SUMMARY-REC
    END-STRING.
    WRITE SUMMARY-REC.

    MOVE SPACES TO SUMMARY-REC.
    STRING "applied_amount_cents=" DELIMITED BY SIZE
        WS-APPLIED-AMOUNT DELIMITED BY SIZE
        INTO SUMMARY-REC
    END-STRING.
    WRITE SUMMARY-REC.

    MOVE SPACES TO SUMMARY-REC.
    STRING "unapplied_count=" DELIMITED BY SIZE
        WS-UNAPPLIED-COUNT DELIMITED BY SIZE
        INTO SUMMARY-REC
    END-STRING.
    WRITE SUMMARY-REC.

    MOVE SPACES TO SUMMARY-REC.
    STRING "unapplied_amount_cents=" DELIMITED BY SIZE
        WS-UNAPPLIED-AMOUNT DELIMITED BY SIZE
        INTO SUMMARY-REC
    END-STRING.
    WRITE SUMMARY-REC.
    CLOSE SUMMARY-FILE.
