#!/bin/bash
set -euo pipefail
cat > /app/src/rollup_batch.pli <<'PLI'
/* numeric directive rollup processor batch control deck */
%SET KEY_COMPARE FULL
%SET CONSUME ON
%SET VALIDATE_MODE ON
%SET ALIAS_MODE ON
%SET WINDOW_MODE ON
%SET CONTROL_MODE ON
%SET DOWNSTREAM_MODE ON
%SET GROUP_MODE ON
%SET LEDGER_MODE ON
%SET CUTOFF_MODE ON
%SET CAPACITY_MODE ON
%SET HOLD_MODE ON
%SET RESTART_MODE ON
%SET SEQUENCE_MODE ON
PLI
