       IDENTIFICATION DIVISION.
       PROGRAM-ID. STMT-MERGE.

       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
           SELECT STM-FILE ASSIGN TO WS-STM-PATH
               ORGANIZATION IS LINE SEQUENTIAL
               FILE STATUS IS WS-STM-STATUS.
           SELECT MANIFEST-FILE ASSIGN TO "/app/config/stream_manifest.txt"
               ORGANIZATION IS LINE SEQUENTIAL.
           SELECT JOB-FILE ASSIGN TO "/app/config/job.properties"
               ORGANIZATION IS LINE SEQUENTIAL.
           SELECT CTL-FILE ASSIGN TO "/app/out/control_totals.dat"
               ORGANIZATION IS LINE SEQUENTIAL.
           SELECT SUMMARY-FILE ASSIGN TO "/app/out/merge_summary.txt"
               ORGANIZATION IS LINE SEQUENTIAL.
           SELECT CHECKPOINT-FILE ASSIGN TO "/app/out/checkpoint.dat"
               ORGANIZATION IS LINE SEQUENTIAL.

       DATA DIVISION.
       FILE SECTION.
       FD STM-FILE.
       01 STM-LINE PIC X(80).
       FD MANIFEST-FILE.
       01 MANIFEST-LINE PIC X(128).
       FD JOB-FILE.
       01 JOB-LINE PIC X(80).
       FD CTL-FILE.
       01 CTL-OUT-REC.
          05 CTL-TYPE           PIC X.
          05 CTL-ACCOUNT        PIC X(8).
          05 CTL-STMT-DATE      PIC X(8).
          05 CTL-DEBIT          PIC 9(10).
          05 CTL-CREDIT         PIC 9(10).
          05 CTL-COUNT          PIC 9(10).
          05 CTL-STATUS         PIC X.
          05 CTL-FILLER         PIC X(8).
       FD SUMMARY-FILE.
       01 SUMMARY-LINE PIC X(80).
       FD CHECKPOINT-FILE.
       01 WS-CKPT-REC.
          05 CKPT-COMPOSITE     PIC X(21).
          05 CKPT-FILE-NUM      PIC 9(2).
          05 CKPT-RECORD-NUM    PIC 9(6).
          05 CKPT-ROW-COUNT     PIC 9(8).
          05 CKPT-PEND-DEBIT    PIC 9(10).
          05 CKPT-PEND-CREDIT   PIC 9(10).
          05 CKPT-PEND-COUNT    PIC 9(10).
          05 CKPT-PEND-GROUP    PIC X(16).
          05 CKPT-COMM-GROUPS    PIC 9(6).
          05 CKPT-TOT-DEBIT      PIC 9(10).
          05 CKPT-TOT-CREDIT     PIC 9(10).

       WORKING-STORAGE SECTION.
       01 STM-IN-REC.
          05 STM-TYPE           PIC X.
          05 STM-ACCOUNT        PIC X(8).
          05 STM-STMT-DATE      PIC X(8).
          05 STM-SEQ            PIC X(5).
          05 STM-TXN-TYPE       PIC X(2).
          05 STM-AMOUNT         PIC 9(10).
          05 STM-STREAM-TAG     PIC X(14).
       01 STM-COMPOSITE-KEY     PIC X(21).
       01 STM-GROUP-KEY         PIC X(16).

       01 WS-STM-PATH PIC X(128) VALUE SPACES.
       01 WS-STM-STATUS PIC XX VALUE SPACES.
       01 WS-EOF-STM PIC X VALUE "N".
       01 WS-EOF-MAN PIC X VALUE "N".
       01 WS-PEEK-IDX PIC 9(2) VALUE 0.
       01 WS-EOF-JOB PIC X VALUE "N".

       01 WS-MANIFEST-COUNT PIC 9(2) VALUE 0.
       01 WS-MANIFEST-IDX PIC 9(2) VALUE 0.
       01 WS-CURRENT-FILE-NUM PIC 9(2) VALUE 0.
       01 WS-FILE-RECORD-NUM PIC 9(6) VALUE 0.
       01 WS-ROW-COUNT PIC 9(8) VALUE 0.

       01 WS-MANIFEST-TABLE.
          05 WS-MAN-ENTRY OCCURS 8 TIMES.
             10 WS-MAN-NUM PIC X(2).
             10 WS-MAN-PATH PIC X(120).

       01 WS-COMMIT-CYCLE PIC X(8) VALUE "20260401".
       01 WS-COMMIT-EVERY PIC 9(4) VALUE 3.

       01 WS-PENDING-ACCOUNT PIC X(8) VALUE SPACES.
       01 WS-PENDING-DATE PIC X(8) VALUE SPACES.
       01 WS-PENDING-GROUP PIC X(16) VALUE SPACES.
       01 WS-PENDING-DEBIT PIC 9(10) VALUE 0.
       01 WS-PENDING-CREDIT PIC 9(10) VALUE 0.
       01 WS-PENDING-COUNT PIC 9(10) VALUE 0.

       01 WS-LAST-ACCOUNT PIC X(8) VALUE SPACES.
       01 WS-LAST-COMPOSITE PIC X(21) VALUE SPACES.
       01 WS-LAST-COMPOSITE-FLAG PIC X VALUE "N".

       01 WS-FLUSH-ACCOUNT PIC X(8) VALUE SPACES.
       01 WS-FLUSH-DATE PIC X(8) VALUE SPACES.

       01 WS-COMMITTED-GROUPS PIC 9(8) VALUE 0.
       01 WS-TOTAL-DEBIT PIC 9(12) VALUE 0.
       01 WS-TOTAL-CREDIT PIC 9(12) VALUE 0.
       01 WS-CHECKPOINT-COMMITS PIC 9(8) VALUE 0.

       01 WS-ABEND-AFTER PIC 9(8) VALUE 0.
       01 WS-ABEND-LIMIT PIC X(16) VALUE SPACES.
       01 WS-RESTART-FLAG PIC X VALUE "N".
       01 WS-RESTART-ENV PIC X(16) VALUE SPACES.

       01 WS-WORK-AMOUNT PIC 9(10) VALUE 0.
       01 WS-DSP PIC Z(10)9.

       PROCEDURE DIVISION.
       MAIN-PARA.
           CALL "SYSTEM" USING "mkdir -p /app/out"
           PERFORM LOAD-JOB-CONFIG
           PERFORM READ-RUNTIME-FLAGS
           PERFORM LOAD-MANIFEST
           OPEN OUTPUT CTL-FILE
           OPEN OUTPUT SUMMARY-FILE
           PERFORM VARYING WS-MANIFEST-IDX FROM 1 BY 1
               UNTIL WS-MANIFEST-IDX > WS-MANIFEST-COUNT
               MOVE WS-MANIFEST-IDX TO WS-CURRENT-FILE-NUM
               PERFORM OPEN-STREAM
               PERFORM PROCESS-STREAM
               PERFORM CLOSE-STREAM
               IF WS-MANIFEST-IDX < WS-MANIFEST-COUNT
                   PERFORM FILE-TRANSITION-FLUSH
               END-IF
           END-PERFORM
           PERFORM COMMIT-PENDING-GROUP
           PERFORM WRITE-SUMMARY
           CLOSE CTL-FILE
           CLOSE SUMMARY-FILE
           STOP RUN.

       LOAD-JOB-CONFIG.
           OPEN INPUT JOB-FILE
           PERFORM UNTIL WS-EOF-JOB = "Y"
               READ JOB-FILE
                   AT END MOVE "Y" TO WS-EOF-JOB
                   NOT AT END
                       IF JOB-LINE(1:13) = "commit_cycle="
                           MOVE JOB-LINE(14:8) TO WS-COMMIT-CYCLE
                       END-IF
                       IF JOB-LINE(1:13) = "commit_every="
                           MOVE JOB-LINE(14:4) TO WS-COMMIT-EVERY
                       END-IF
               END-READ
           END-PERFORM
           CLOSE JOB-FILE.

       READ-RUNTIME-FLAGS.
           MOVE SPACES TO WS-ABEND-LIMIT
           ACCEPT WS-ABEND-LIMIT FROM ENVIRONMENT "STMT_MERGE_ABEND_AFTER"
           IF WS-ABEND-LIMIT NOT = SPACES
               MOVE WS-ABEND-LIMIT TO WS-ABEND-AFTER
           END-IF
           MOVE SPACES TO WS-RESTART-ENV
           ACCEPT WS-RESTART-ENV FROM ENVIRONMENT "STMT_MERGE_RESTART"
           IF WS-RESTART-ENV = "1"
               MOVE "Y" TO WS-RESTART-FLAG
           END-IF.

       LOAD-MANIFEST.
           OPEN INPUT MANIFEST-FILE
           PERFORM UNTIL WS-EOF-MAN = "Y"
               READ MANIFEST-FILE
                   AT END MOVE "Y" TO WS-EOF-MAN
                   NOT AT END
                       IF MANIFEST-LINE(1:1) NOT = SPACES
                           ADD 1 TO WS-MANIFEST-COUNT
                           MOVE MANIFEST-LINE(1:2) TO WS-MAN-NUM(WS-MANIFEST-COUNT)
                           MOVE MANIFEST-LINE(4:120) TO WS-MAN-PATH(WS-MANIFEST-COUNT)
                       END-IF
               END-READ
           END-PERFORM
           CLOSE MANIFEST-FILE.

       OPEN-STREAM.
           MOVE WS-MAN-PATH(WS-MANIFEST-IDX) TO WS-STM-PATH
           MOVE ZERO TO WS-FILE-RECORD-NUM
           MOVE ZERO TO WS-PENDING-DEBIT
           MOVE ZERO TO WS-PENDING-CREDIT
           MOVE ZERO TO WS-PENDING-COUNT
           MOVE SPACES TO WS-PENDING-GROUP
           MOVE SPACES TO WS-PENDING-ACCOUNT
           MOVE SPACES TO WS-PENDING-DATE
           MOVE SPACES TO WS-LAST-COMPOSITE
           MOVE "N" TO WS-LAST-COMPOSITE-FLAG
           OPEN INPUT STM-FILE.

       CLOSE-STREAM.
           CLOSE STM-FILE.

       PROCESS-STREAM.
           MOVE "N" TO WS-EOF-STM
           PERFORM UNTIL WS-EOF-STM = "Y"
               READ STM-FILE
                   AT END MOVE "Y" TO WS-EOF-STM
                   NOT AT END
                       ADD 1 TO WS-FILE-RECORD-NUM
                       PERFORM HANDLE-STATEMENT
               END-READ
           END-PERFORM.

       HANDLE-STATEMENT.
           MOVE STM-LINE TO STM-IN-REC
           IF STM-TYPE NOT = "S"
               GO TO HANDLE-DONE
           END-IF
           MOVE STM-ACCOUNT TO STM-GROUP-KEY(1:8)
           MOVE STM-STMT-DATE TO STM-GROUP-KEY(9:8)
           STRING STM-ACCOUNT DELIMITED BY SIZE
               STM-STMT-DATE DELIMITED BY SIZE
               STM-SEQ DELIMITED BY SIZE
               INTO STM-COMPOSITE-KEY
           END-STRING
           IF WS-LAST-ACCOUNT NOT = SPACES
               AND STM-ACCOUNT NOT = WS-LAST-ACCOUNT
               PERFORM COMMIT-PENDING-GROUP
           END-IF
           IF STM-TXN-TYPE = "DR"
               ADD STM-AMOUNT TO WS-PENDING-DEBIT
           ELSE
               IF STM-TXN-TYPE = "CR"
                   ADD STM-AMOUNT TO WS-PENDING-CREDIT
               END-IF
           END-IF
           ADD 1 TO WS-PENDING-COUNT
           ADD 1 TO WS-ROW-COUNT
           MOVE STM-ACCOUNT TO WS-PENDING-ACCOUNT
           MOVE STM-STMT-DATE TO WS-PENDING-DATE
           MOVE STM-GROUP-KEY TO WS-PENDING-GROUP
           MOVE STM-ACCOUNT TO WS-LAST-ACCOUNT
           MOVE STM-COMPOSITE-KEY TO WS-LAST-COMPOSITE
           MOVE "Y" TO WS-LAST-COMPOSITE-FLAG
           IF WS-ABEND-AFTER > 0 AND WS-ROW-COUNT >= WS-ABEND-AFTER
               PERFORM WRITE-CHECKPOINT
               STOP RUN 99
           END-IF
           IF FUNCTION MOD(WS-ROW-COUNT, WS-COMMIT-EVERY) = 0
               PERFORM WRITE-CHECKPOINT
           END-IF
           .

       HANDLE-DONE.
           EXIT.

       FILE-TRANSITION-FLUSH.
           COMPUTE WS-PEEK-IDX = WS-MANIFEST-IDX + 1
           MOVE WS-MAN-PATH(WS-PEEK-IDX) TO WS-STM-PATH
           OPEN INPUT STM-FILE
           READ STM-FILE
               AT END CONTINUE
               NOT AT END
                   MOVE STM-LINE TO STM-IN-REC
                   MOVE STM-ACCOUNT TO WS-FLUSH-ACCOUNT
                   MOVE STM-STMT-DATE TO WS-FLUSH-DATE
           END-READ
           CLOSE STM-FILE
           IF WS-PENDING-COUNT > 0
               PERFORM COMMIT-PENDING-GROUP
           END-IF.

       COMMIT-PENDING-GROUP.
           IF WS-PENDING-COUNT = 0
               GO TO COMMIT-DONE
           END-IF
           IF WS-FLUSH-ACCOUNT NOT = SPACES
               MOVE WS-FLUSH-ACCOUNT TO CTL-ACCOUNT
               MOVE WS-FLUSH-DATE TO CTL-STMT-DATE
           ELSE
               MOVE WS-PENDING-ACCOUNT TO CTL-ACCOUNT
               MOVE WS-PENDING-DATE TO CTL-STMT-DATE
           END-IF
           MOVE "T" TO CTL-TYPE
           MOVE WS-PENDING-DEBIT TO CTL-DEBIT
           MOVE WS-PENDING-CREDIT TO CTL-CREDIT
           MOVE WS-PENDING-COUNT TO CTL-COUNT
           MOVE "C" TO CTL-STATUS
           MOVE SPACES TO CTL-FILLER
           WRITE CTL-OUT-REC
           ADD WS-PENDING-DEBIT TO WS-TOTAL-DEBIT
           ADD WS-PENDING-CREDIT TO WS-TOTAL-CREDIT
           ADD 1 TO WS-COMMITTED-GROUPS
           MOVE ZERO TO WS-PENDING-DEBIT
           MOVE ZERO TO WS-PENDING-CREDIT
           MOVE ZERO TO WS-PENDING-COUNT
           MOVE SPACES TO WS-PENDING-GROUP
           MOVE SPACES TO WS-FLUSH-ACCOUNT
           MOVE SPACES TO WS-FLUSH-DATE
           .

       COMMIT-DONE.
           EXIT.

       WRITE-CHECKPOINT.
           OPEN OUTPUT CHECKPOINT-FILE
           MOVE WS-LAST-COMPOSITE TO CKPT-COMPOSITE
           MOVE WS-CURRENT-FILE-NUM TO CKPT-FILE-NUM
           MOVE WS-FILE-RECORD-NUM TO CKPT-RECORD-NUM
           MOVE WS-ROW-COUNT TO CKPT-ROW-COUNT
           MOVE WS-PENDING-DEBIT TO CKPT-PEND-DEBIT
           MOVE WS-PENDING-CREDIT TO CKPT-PEND-CREDIT
           MOVE WS-PENDING-COUNT TO CKPT-PEND-COUNT
           MOVE WS-PENDING-GROUP TO CKPT-PEND-GROUP
           MOVE WS-COMMITTED-GROUPS TO CKPT-COMM-GROUPS
           MOVE WS-TOTAL-DEBIT TO CKPT-TOT-DEBIT
           MOVE WS-TOTAL-CREDIT TO CKPT-TOT-CREDIT
           WRITE WS-CKPT-REC
           CLOSE CHECKPOINT-FILE
           ADD 1 TO WS-CHECKPOINT-COMMITS.

       WRITE-SUMMARY.
           MOVE WS-COMMITTED-GROUPS TO WS-DSP
           MOVE SPACES TO SUMMARY-LINE
           STRING "committed_groups=" DELIMITED BY SIZE
               FUNCTION TRIM(WS-DSP LEADING) DELIMITED BY SIZE
               INTO SUMMARY-LINE END-STRING
           WRITE SUMMARY-LINE
           MOVE WS-TOTAL-DEBIT TO WS-DSP
           MOVE SPACES TO SUMMARY-LINE
           STRING "total_debit_cents=" DELIMITED BY SIZE
               FUNCTION TRIM(WS-DSP LEADING) DELIMITED BY SIZE
               INTO SUMMARY-LINE END-STRING
           WRITE SUMMARY-LINE
           MOVE WS-TOTAL-CREDIT TO WS-DSP
           MOVE SPACES TO SUMMARY-LINE
           STRING "total_credit_cents=" DELIMITED BY SIZE
               FUNCTION TRIM(WS-DSP LEADING) DELIMITED BY SIZE
               INTO SUMMARY-LINE END-STRING
           WRITE SUMMARY-LINE
           MOVE WS-ROW-COUNT TO WS-DSP
           MOVE SPACES TO SUMMARY-LINE
           STRING "statement_rows=" DELIMITED BY SIZE
               FUNCTION TRIM(WS-DSP LEADING) DELIMITED BY SIZE
               INTO SUMMARY-LINE END-STRING
           WRITE SUMMARY-LINE
           MOVE WS-CHECKPOINT-COMMITS TO WS-DSP
           MOVE SPACES TO SUMMARY-LINE
           STRING "checkpoint_commits=" DELIMITED BY SIZE
               FUNCTION TRIM(WS-DSP LEADING) DELIMITED BY SIZE
               INTO SUMMARY-LINE END-STRING
           WRITE SUMMARY-LINE
           .
