#!/bin/bash
set -euo pipefail
cat > /app/src/rollup_batch.pli <<'PLI'
/* numeric directive rollup processor batch control deck */
%SET KEY_COMPARE FULL
%SET CONSUME ON
%SET VALIDATE_MODE ON
%SET ALIAS_MODE ON
%SET WINDOW_MODE ON
%SET CONTROL_MODE ON
%SET DOWNSTREAM_MODE ON
%SET GROUP_MODE ON
%SET LEDGER_MODE OFF
%SET CUTOFF_MODE OFF
%SET CAPACITY_MODE OFF
%SET HOLD_MODE OFF
%SET RESTART_MODE OFF
%SET SEQUENCE_MODE OFF
PLI
