#!/usr/bin/env bash
set -euo pipefail

cd /app

cat > /app/src/ach_reconcile.cbl <<'CBL'
       >>SOURCE FORMAT FREE
IDENTIFICATION DIVISION.
PROGRAM-ID. ACHRECON.

ENVIRONMENT DIVISION.
INPUT-OUTPUT SECTION.
FILE-CONTROL.
    SELECT SETTLE-FILE ASSIGN TO "/app/data/settlement.dat"
        ORGANIZATION IS LINE SEQUENTIAL.
    SELECT REVERSAL-FILE ASSIGN TO "/app/data/reversals.dat"
        ORGANIZATION IS LINE SEQUENTIAL.
    SELECT CALENDAR-FILE ASSIGN TO "/app/config/business_calendar.txt"
        ORGANIZATION IS LINE SEQUENTIAL.
    SELECT REPORT-FILE ASSIGN TO "/app/out/reversal_report.csv"
        ORGANIZATION IS LINE SEQUENTIAL.
    SELECT SUMMARY-FILE ASSIGN TO "/app/out/reversal_summary.txt"
        ORGANIZATION IS LINE SEQUENTIAL.

DATA DIVISION.
FILE SECTION.
FD SETTLE-FILE.
01 SETTLE-REC PIC X(47).
FD REVERSAL-FILE.
01 REVERSAL-REC PIC X(45).
FD CALENDAR-FILE.
01 CALENDAR-REC PIC X(16).
FD REPORT-FILE.
01 REPORT-REC PIC X(160).
FD SUMMARY-FILE.
01 SUMMARY-REC PIC X(80).

WORKING-STORAGE SECTION.
01 EOF-SETTLE PIC X VALUE "N".
01 EOF-REVERSAL PIC X VALUE "N".
01 EOF-CALENDAR PIC X VALUE "N".
01 WS-IDX PIC 9(4) COMP VALUE 0.
01 WS-CAL-IDX PIC 9(4) COMP VALUE 0.
01 WS-MATCH-IDX PIC 9(4) COMP VALUE 0.
01 WS-SETTLE-COUNT PIC 9(4) COMP VALUE 0.
01 WS-CAL-COUNT PIC 9(4) COMP VALUE 0.
01 WS-MATCHED-COUNT PIC 9(5) VALUE 0.
01 WS-UNMATCHED-COUNT PIC 9(5) VALUE 0.
01 WS-MATCHED-AMOUNT PIC S9(12) SIGN LEADING SEPARATE VALUE 0.
01 WS-UNMATCHED-AMOUNT PIC 9(12) VALUE 0.
01 WS-BANK-DAYS PIC 9(3) VALUE 0.
01 WS-DATE-FOUND PIC X VALUE "N".
01 WS-TARGET-DATE PIC X(8).
01 WS-DATE-OPEN PIC X VALUE "N".
01 WS-SET-DATE-OPEN PIC X VALUE "N".
01 WS-REV-DATE-OPEN PIC X VALUE "N".
01 WS-CAL-STATUS PIC X(4).

01 WS-REV-TRACE PIC X(15).
01 WS-REV-REASON PIC X(3).
01 WS-REV-AMOUNT-TEXT PIC X(10).
01 WS-REV-AMOUNT PIC 9(10).
01 WS-REV-DATE PIC X(8).
01 WS-REV-COMPANY PIC X(8).
01 WS-STATUS PIC X(9).

01 CALENDAR-TABLE.
   05 CALENDAR-ENTRY OCCURS 500 TIMES.
      10 CAL-DATE PIC X(8).
      10 CAL-OPEN PIC X.

01 SETTLE-TABLE.
   05 SETTLE-ENTRY OCCURS 300 TIMES.
      10 SET-TRACE PIC X(15).
      10 SET-SEC PIC X(3).
      10 SET-AMOUNT PIC 9(10).
      10 SET-DIRECTION PIC X.
      10 SET-DATE PIC X(8).
      10 SET-COMPANY PIC X(8).
      10 SET-STATUS PIC X.
      10 SET-USED PIC X.

PROCEDURE DIVISION.
MAIN.
    PERFORM LOAD-CALENDAR.
    PERFORM LOAD-SETTLEMENTS.
    PERFORM WRITE-REPORT-HEADER.
    PERFORM PROCESS-REVERSALS.
    PERFORM WRITE-SUMMARY.
    STOP RUN.

LOAD-CALENDAR.
    OPEN INPUT CALENDAR-FILE.
    PERFORM UNTIL EOF-CALENDAR = "Y"
        READ CALENDAR-FILE
            AT END
                MOVE "Y" TO EOF-CALENDAR
            NOT AT END
                IF CALENDAR-REC(1:8) NOT = SPACES
                    MOVE FUNCTION UPPER-CASE(CALENDAR-REC(10:4)) TO WS-CAL-STATUS
                    MOVE "N" TO WS-DATE-FOUND
                    PERFORM VARYING WS-CAL-IDX FROM 1 BY 1
                        UNTIL WS-CAL-IDX > WS-CAL-COUNT
                        IF CAL-DATE(WS-CAL-IDX) = CALENDAR-REC(1:8)
                            MOVE "Y" TO WS-DATE-FOUND
                            IF WS-CAL-STATUS = "OPEN"
                                MOVE "Y" TO CAL-OPEN(WS-CAL-IDX)
                            ELSE
                                MOVE "N" TO CAL-OPEN(WS-CAL-IDX)
                            END-IF
                        END-IF
                    END-PERFORM
                    IF WS-DATE-FOUND NOT = "Y"
                        ADD 1 TO WS-CAL-COUNT
                        MOVE CALENDAR-REC(1:8) TO CAL-DATE(WS-CAL-COUNT)
                        IF WS-CAL-STATUS = "OPEN"
                            MOVE "Y" TO CAL-OPEN(WS-CAL-COUNT)
                        ELSE
                            MOVE "N" TO CAL-OPEN(WS-CAL-COUNT)
                        END-IF
                    END-IF
                END-IF
        END-READ
    END-PERFORM.
    CLOSE CALENDAR-FILE.

LOAD-SETTLEMENTS.
    OPEN INPUT SETTLE-FILE.
    PERFORM UNTIL EOF-SETTLE = "Y"
        READ SETTLE-FILE
            AT END
                MOVE "Y" TO EOF-SETTLE
            NOT AT END
                IF SETTLE-REC(1:1) = "S"
                    ADD 1 TO WS-SETTLE-COUNT
                    MOVE SETTLE-REC(2:15) TO SET-TRACE(WS-SETTLE-COUNT)
                    MOVE SETTLE-REC(17:3) TO SET-SEC(WS-SETTLE-COUNT)
                    MOVE SETTLE-REC(20:10) TO SET-AMOUNT(WS-SETTLE-COUNT)
                    MOVE SETTLE-REC(30:1) TO SET-DIRECTION(WS-SETTLE-COUNT)
                    MOVE SETTLE-REC(31:8) TO SET-DATE(WS-SETTLE-COUNT)
                    MOVE SETTLE-REC(39:8) TO SET-COMPANY(WS-SETTLE-COUNT)
                    MOVE SETTLE-REC(47:1) TO SET-STATUS(WS-SETTLE-COUNT)
                    MOVE "N" TO SET-USED(WS-SETTLE-COUNT)
                END-IF
        END-READ
    END-PERFORM.
    CLOSE SETTLE-FILE.

WRITE-REPORT-HEADER.
    OPEN OUTPUT REPORT-FILE.
    MOVE "trace,company,sec,amount_cents,reason,status" TO REPORT-REC.
    WRITE REPORT-REC.

PROCESS-REVERSALS.
    OPEN INPUT REVERSAL-FILE.
    PERFORM UNTIL EOF-REVERSAL = "Y"
        READ REVERSAL-FILE
            AT END
                MOVE "Y" TO EOF-REVERSAL
            NOT AT END
                IF REVERSAL-REC(1:1) = "R"
                    PERFORM PARSE-REVERSAL
                    PERFORM FIND-MATCH
                    IF WS-MATCH-IDX > 0
                        MOVE "MATCHED" TO WS-STATUS
                        ADD 1 TO WS-MATCHED-COUNT
                        ADD WS-REV-AMOUNT TO WS-MATCHED-AMOUNT
                        MOVE "Y" TO SET-USED(WS-MATCH-IDX)
                    ELSE
                        MOVE "UNMATCHED" TO WS-STATUS
                        ADD 1 TO WS-UNMATCHED-COUNT
                        ADD WS-REV-AMOUNT TO WS-UNMATCHED-AMOUNT
                    END-IF
                    PERFORM WRITE-REPORT-ROW
                END-IF
        END-READ
    END-PERFORM.
    CLOSE REVERSAL-FILE.
    CLOSE REPORT-FILE.

PARSE-REVERSAL.
    MOVE REVERSAL-REC(2:15) TO WS-REV-TRACE.
    MOVE REVERSAL-REC(17:3) TO WS-REV-REASON.
    MOVE REVERSAL-REC(20:10) TO WS-REV-AMOUNT-TEXT.
    MOVE REVERSAL-REC(20:10) TO WS-REV-AMOUNT.
    MOVE REVERSAL-REC(30:8) TO WS-REV-DATE.
    MOVE REVERSAL-REC(38:8) TO WS-REV-COMPANY.

FIND-MATCH.
    MOVE 0 TO WS-MATCH-IDX.
    PERFORM VARYING WS-IDX FROM 1 BY 1
        UNTIL WS-IDX > WS-SETTLE-COUNT
        MOVE SET-DATE(WS-IDX) TO WS-TARGET-DATE
        PERFORM CHECK-DATE-OPEN
        MOVE WS-DATE-OPEN TO WS-SET-DATE-OPEN
        MOVE WS-REV-DATE TO WS-TARGET-DATE
        PERFORM CHECK-DATE-OPEN
        MOVE WS-DATE-OPEN TO WS-REV-DATE-OPEN
        PERFORM COUNT-BUSINESS-DAYS
        IF SET-USED(WS-IDX) NOT = "Y"
            AND WS-SET-DATE-OPEN = "Y"
            AND WS-REV-DATE-OPEN = "Y"
            AND SET-TRACE(WS-IDX) = WS-REV-TRACE
            AND SET-COMPANY(WS-IDX) = WS-REV-COMPANY
            AND SET-AMOUNT(WS-IDX) = WS-REV-AMOUNT
            AND SET-DIRECTION(WS-IDX) = "C"
            AND SET-STATUS(WS-IDX) = "P"
            AND WS-REV-DATE >= SET-DATE(WS-IDX)
            AND ((WS-REV-REASON = "R01" AND WS-BANK-DAYS <= 1)
                 OR (WS-REV-REASON = "R02" AND WS-BANK-DAYS <= 1)
                 OR (WS-REV-REASON = "R03" AND WS-BANK-DAYS <= 2)
                 OR (WS-REV-REASON = "R10" AND WS-BANK-DAYS <= 2))
            AND (SET-SEC(WS-IDX) = "PPD"
                 OR SET-SEC(WS-IDX) = "CCD"
                 OR SET-SEC(WS-IDX) = "WEB"
                 OR SET-SEC(WS-IDX) = "TEL")
                IF WS-MATCH-IDX = 0
                    MOVE WS-IDX TO WS-MATCH-IDX
                ELSE
                    IF SET-DATE(WS-IDX) > SET-DATE(WS-MATCH-IDX)
                        MOVE WS-IDX TO WS-MATCH-IDX
                    END-IF
                END-IF
        END-IF
    END-PERFORM.

CHECK-DATE-OPEN.
    MOVE "N" TO WS-DATE-OPEN.
    PERFORM VARYING WS-CAL-IDX FROM 1 BY 1
        UNTIL WS-CAL-IDX > WS-CAL-COUNT
        IF CAL-DATE(WS-CAL-IDX) = WS-TARGET-DATE
            AND CAL-OPEN(WS-CAL-IDX) = "Y"
                MOVE "Y" TO WS-DATE-OPEN
        END-IF
    END-PERFORM.

COUNT-BUSINESS-DAYS.
    MOVE 0 TO WS-BANK-DAYS.
    PERFORM VARYING WS-CAL-IDX FROM 1 BY 1
        UNTIL WS-CAL-IDX > WS-CAL-COUNT
        IF CAL-DATE(WS-CAL-IDX) > SET-DATE(WS-IDX)
            AND CAL-DATE(WS-CAL-IDX) <= WS-REV-DATE
            AND CAL-OPEN(WS-CAL-IDX) = "Y"
                ADD 1 TO WS-BANK-DAYS
        END-IF
    END-PERFORM.

WRITE-REPORT-ROW.
    MOVE SPACES TO REPORT-REC.
    IF WS-MATCH-IDX > 0
        STRING
            WS-REV-TRACE DELIMITED BY SIZE
            "," DELIMITED BY SIZE
            WS-REV-COMPANY DELIMITED BY SIZE
            "," DELIMITED BY SIZE
            SET-SEC(WS-MATCH-IDX) DELIMITED BY SIZE
            "," DELIMITED BY SIZE
            WS-REV-AMOUNT-TEXT DELIMITED BY SIZE
            "," DELIMITED BY SIZE
            WS-REV-REASON DELIMITED BY SIZE
            "," DELIMITED BY SIZE
            WS-STATUS DELIMITED BY SPACE
            INTO REPORT-REC
        END-STRING
    ELSE
        STRING
            WS-REV-TRACE DELIMITED BY SIZE
            "," DELIMITED BY SIZE
            WS-REV-COMPANY DELIMITED BY SIZE
            ",," DELIMITED BY SIZE
            WS-REV-AMOUNT-TEXT DELIMITED BY SIZE
            "," DELIMITED BY SIZE
            WS-REV-REASON DELIMITED BY SIZE
            ",UNMATCHED" DELIMITED BY SIZE
            INTO REPORT-REC
        END-STRING
    END-IF.
    WRITE REPORT-REC.

WRITE-SUMMARY.
    OPEN OUTPUT SUMMARY-FILE.
    MOVE SPACES TO SUMMARY-REC.
    STRING "matched_count=" DELIMITED BY SIZE
        WS-MATCHED-COUNT DELIMITED BY SIZE
        INTO SUMMARY-REC
    END-STRING.
    WRITE SUMMARY-REC.
    MOVE SPACES TO SUMMARY-REC.
    STRING "matched_amount_cents=" DELIMITED BY SIZE
        WS-MATCHED-AMOUNT DELIMITED BY SIZE
        INTO SUMMARY-REC
    END-STRING.
    WRITE SUMMARY-REC.
    MOVE SPACES TO SUMMARY-REC.
    STRING "unmatched_count=" DELIMITED BY SIZE
        WS-UNMATCHED-COUNT DELIMITED BY SIZE
        INTO SUMMARY-REC
    END-STRING.
    WRITE SUMMARY-REC.
    MOVE SPACES TO SUMMARY-REC.
    STRING "unmatched_amount_cents=" DELIMITED BY SIZE
        WS-UNMATCHED-AMOUNT DELIMITED BY SIZE
        INTO SUMMARY-REC
    END-STRING.
    WRITE SUMMARY-REC.
    CLOSE SUMMARY-FILE.
CBL

/app/scripts/run_batch.sh
