IDENTIFICATION DIVISION.
PROGRAM-ID. catclaim-router.
ENVIRONMENT DIVISION.
INPUT-OUTPUT SECTION.
FILE-CONTROL.
    SELECT CLAIMS-FILE ASSIGN TO "/app/data/claims.psv"
        ORGANIZATION IS LINE SEQUENTIAL FILE STATUS IS WS-FS.
    SELECT POLICIES-FILE ASSIGN TO "/app/data/policies.psv"
        ORGANIZATION IS LINE SEQUENTIAL FILE STATUS IS WS-FS.
    SELECT DIAG-FILE ASSIGN TO "/app/config/diagnosis_policy.psv"
        ORGANIZATION IS LINE SEQUENTIAL FILE STATUS IS WS-FS.
    SELECT FAC-FILE ASSIGN TO "/app/config/facility_trust.psv"
        ORGANIZATION IS LINE SEQUENTIAL FILE STATUS IS WS-FS.
    SELECT DECK-FILE ASSIGN TO "/app/config/payment_policy.pli"
        ORGANIZATION IS LINE SEQUENTIAL FILE STATUS IS WS-FS.
    SELECT REJ-PREC-FILE ASSIGN TO "/app/config/reject_precedence.psv"
        ORGANIZATION IS LINE SEQUENTIAL FILE STATUS IS WS-FS.
    SELECT REV-PREC-FILE ASSIGN TO "/app/config/review_reason_precedence.psv"
        ORGANIZATION IS LINE SEQUENTIAL FILE STATUS IS WS-FS.
    SELECT BANK-FILE ASSIGN TO "/app/data/bank_verification_responses.psv"
        ORGANIZATION IS LINE SEQUENTIAL FILE STATUS IS WS-FS.
    SELECT PRIOR-LED-FILE ASSIGN TO "/app/data/prior_disbursement_ledger.psv"
        ORGANIZATION IS LINE SEQUENTIAL FILE STATUS IS WS-FS.
    SELECT OUT-LED-FILE ASSIGN TO "/app/out/payment_ledger.psv"
        ORGANIZATION IS LINE SEQUENTIAL FILE STATUS IS WS-FS.
    SELECT DECISIONS-FILE ASSIGN TO "/app/out/payment_decision_report.psv"
        ORGANIZATION IS LINE SEQUENTIAL.
    SELECT REJECTS-FILE ASSIGN TO "/app/out/reject_ledger.psv"
        ORGANIZATION IS LINE SEQUENTIAL.
    SELECT REVIEWS-FILE ASSIGN TO "/app/out/manual_review_queue.psv"
        ORGANIZATION IS LINE SEQUENTIAL FILE STATUS IS WS-FS.
    SELECT CHECKS-FILE ASSIGN TO "/app/out/check_queue.psv"
        ORGANIZATION IS LINE SEQUENTIAL FILE STATUS IS WS-FS.
    SELECT EFT-FILE ASSIGN TO "/app/out/eft_queue.psv"
        ORGANIZATION IS LINE SEQUENTIAL FILE STATUS IS WS-FS.
    SELECT VERIFY-FILE ASSIGN TO "/app/out/bank_verify_messages.psv"
        ORGANIZATION IS LINE SEQUENTIAL FILE STATUS IS WS-FS.
    SELECT CONTROL-FILE ASSIGN TO "/app/out/control_totals.psv"
        ORGANIZATION IS LINE SEQUENTIAL.
    SELECT CHECKPOINT-FILE ASSIGN TO "/app/out/restart_checkpoint.txt"
        ORGANIZATION IS LINE SEQUENTIAL FILE STATUS IS WS-FS.
DATA DIVISION.
FILE SECTION.
FD CLAIMS-FILE.
01 CLAIM-LINE PIC X(512).
FD POLICIES-FILE.
01 POLICY-LINE PIC X(256).
FD DIAG-FILE.
01 DIAG-LINE PIC X(128).
FD FAC-FILE.
01 FAC-LINE PIC X(128).
FD DECK-FILE.
01 DECK-LINE PIC X(256).
FD REJ-PREC-FILE.
01 REJ-PREC-LINE PIC X(128).
FD REV-PREC-FILE.
01 REV-PREC-LINE PIC X(128).
FD BANK-FILE.
01 BANK-LINE PIC X(256).
FD PRIOR-LED-FILE.
01 PRIOR-LED-LINE PIC X(256).
FD OUT-LED-FILE.
01 OUT-LED-LINE PIC X(256).
FD DECISIONS-FILE.
01 DECISION-OUT PIC X(512).
FD REJECTS-FILE.
01 REJECT-OUT PIC X(256).
FD REVIEWS-FILE.
01 REVIEW-OUT PIC X(256).
FD CHECKS-FILE.
01 CHECK-OUT PIC X(256).
FD EFT-FILE.
01 EFT-OUT PIC X(256).
FD VERIFY-FILE.
01 VERIFY-OUT PIC X(256).
FD CONTROL-FILE.
01 CONTROL-OUT PIC X(128).
FD CHECKPOINT-FILE.
01 CHECKPOINT-OUT PIC X(256).
WORKING-STORAGE SECTION.
01 WS-STAGE PIC 9 VALUE 4.
01 WS-FS PIC XX.
01 WS-EOF PIC X VALUE "N".
01 WS-IDX PIC 9(4) VALUE 0.
01 WS-JDX PIC 9(4) VALUE 0.
01 WS-KDX PIC 9(4) VALUE 0.
01 WS-FOUND PIC 9(4) VALUE 0.
01 WS-CLAIM-COUNT PIC 9(4) VALUE 0.
01 WS-POL-COUNT PIC 9(4) VALUE 0.
01 WS-DX-COUNT PIC 9(4) VALUE 0.
01 WS-FAC-COUNT PIC 9(4) VALUE 0.
01 WS-BANK-COUNT PIC 9(4) VALUE 0.
01 WS-LED-COUNT PIC 9(4) VALUE 0.
01 WS-EXIST-LED-COUNT PIC 9(4) VALUE 0.
01 WS-REJ-PREC-COUNT PIC 9(4) VALUE 0.
01 WS-REV-PREC-COUNT PIC 9(4) VALUE 0.
01 WS-DEC-COUNT PIC 9(4) VALUE 0.
01 WS-REJ-COUNT PIC 9(4) VALUE 0.
01 WS-REV-COUNT PIC 9(4) VALUE 0.
01 WS-CHK-COUNT PIC 9(4) VALUE 0.
01 WS-EFT-COUNT PIC 9(4) VALUE 0.
01 WS-VER-COUNT PIC 9(4) VALUE 0.
01 WS-EVENT-COUNT PIC 9(4) VALUE 0.
01 WS-COMM-EVENT-COUNT PIC 9(4) VALUE 0.
01 WS-COMM-INST-COUNT PIC 9(4) VALUE 0.
01 WS-TOKEN-COUNT PIC 9(4) VALUE 0.
01 WS-NEW-COMMITS PIC 9(4) VALUE 0.
01 WS-ABEND-LIMIT PIC 9(4) VALUE 0.
01 WS-ABEND-SET PIC X VALUE "N".
01 WS-AMT PIC 9(12) VALUE 0.
01 WS-AMT-W PIC 9(12) VALUE 0.
01 WS-DSP PIC Z(11)9.
01 WS-CNT-DSP PIC Z(8)9.
01 WS-AMT-STR PIC X(16) VALUE SPACES.
01 WS-CNT-STR PIC X(16) VALUE SPACES.
01 WS-EXP-LIMIT PIC 9(12) VALUE 50000.
01 WS-EFT-LIMIT PIC 9(12) VALUE 75000.
01 WS-MAN-LIMIT PIC 9(12) VALUE 125000.
01 WS-REJECT-CODE PIC X(32) VALUE SPACES.
01 WS-REVIEW-CODE PIC X(32) VALUE SPACES.
01 WS-RAIL PIC X(8) VALUE SPACES.
01 WS-PRIORITY PIC X(16) VALUE "NORMAL".
01 WS-REASON-OUT PIC X(32) VALUE SPACES.
01 WS-INST PIC X(80) VALUE SPACES.
01 WS-NORM PIC X(64) VALUE SPACES.
01 WS-TRIM PIC X(64) VALUE SPACES.
01 WS-UPPER PIC X(64) VALUE SPACES.
01 WS-ENV PIC X(32) VALUE SPACES.
01 WS-INIT-START PIC 9(4) VALUE 0.
01 WS-INIT-VAL PIC X(32) VALUE SPACES.
01 WS-LINE-BUF PIC X(512) VALUE SPACES.
01 WS-F1 PIC X(32) VALUE SPACES.
01 WS-F2 PIC X(32) VALUE SPACES.
01 WS-F3 PIC X(32) VALUE SPACES.
01 WS-F4 PIC X(32) VALUE SPACES.
01 WS-F5 PIC X(32) VALUE SPACES.
01 WS-F6 PIC X(32) VALUE SPACES.
01 WS-F7 PIC X(32) VALUE SPACES.
01 WS-F8 PIC X(32) VALUE SPACES.
01 WS-F9 PIC X(32) VALUE SPACES.
01 WS-F10 PIC X(32) VALUE SPACES.
01 WS-F11 PIC X(32) VALUE SPACES.
01 WS-F12 PIC X(32) VALUE SPACES.
01 WS-F13 PIC X(32) VALUE SPACES.
01 WS-F14 PIC X(32) VALUE SPACES.
01 WS-CUR PIC 9(4) VALUE 0.
01 WS-R-FLAG PIC X VALUE "N".
01 WS-REJ-FLAGS.
   05 WS-RF-DUP PIC X VALUE "N".
   05 WS-RF-NOPOL PIC X VALUE "N".
   05 WS-RF-INACT PIC X VALUE "N".
   05 WS-RF-MMEM PIC X VALUE "N".
   05 WS-RF-NOADJ PIC X VALUE "N".
   05 WS-RF-NOCAT PIC X VALUE "N".
   05 WS-RF-AUTH PIC X VALUE "N".
   05 WS-RF-AMT PIC X VALUE "N".
01 WS-REV-FLAGS.
   05 WS-VF-ID PIC X VALUE "N".
   05 WS-VF-SANC PIC X VALUE "N".
   05 WS-VF-NTR PIC X VALUE "N".
   05 WS-VF-BANK PIC X VALUE "N".
   05 WS-VF-MAN PIC X VALUE "N".
01 WS-CLAIM-TABLE.
   05 WS-CL OCCURS 300 TIMES.
      10 WS-CL-CLAIM PIC X(32).
      10 WS-CL-EVENT PIC X(32).
      10 WS-CL-POL PIC X(32).
      10 WS-CL-MEM PIC X(32).
      10 WS-CL-FAC PIC X(32).
      10 WS-CL-DX PIC X(32).
      10 WS-CL-AMT PIC 9(12).
      10 WS-CL-PAYEE PIC X(16).
      10 WS-CL-BANK PIC X(32).
      10 WS-CL-TOKEN PIC X(32).
      10 WS-CL-ADJ PIC X(32).
      10 WS-CL-AUTH PIC X(32).
01 WS-POL-TABLE.
   05 WS-PL OCCURS 200 TIMES.
      10 WS-PL-ID PIC X(32).
      10 WS-PL-MEM PIC X(32).
      10 WS-PL-STAT PIC X(16).
01 WS-DX-TABLE.
   05 WS-DX OCCURS 50 TIMES.
      10 WS-DX-CODE PIC X(32).
      10 WS-DX-CAT PIC X(4).
      10 WS-DX-AUTH PIC X(4).
      10 WS-DX-EXP PIC X(4).
01 WS-FAC-TABLE.
   05 WS-FC OCCURS 50 TIMES.
      10 WS-FC-ID PIC X(32).
      10 WS-FC-TIER PIC X(16).
      10 WS-FC-SANC PIC X(4).
      10 WS-FC-EMER PIC X(4).
01 WS-BANK-TABLE.
   05 WS-BK OCCURS 200 TIMES.
      10 WS-BK-CLAIM PIC X(32).
      10 WS-BK-EVENT PIC X(32).
      10 WS-BK-ACCT PIC X(32).
      10 WS-BK-STAT PIC X(32).
01 WS-REJ-PREC-TABLE.
   05 WS-RP OCCURS 20 TIMES.
      10 WS-RP-RANK PIC 9(4).
      10 WS-RP-CODE PIC X(32).
01 WS-REV-PREC-TABLE.
   05 WS-VP OCCURS 20 TIMES.
      10 WS-VP-RANK PIC 9(4).
      10 WS-VP-CODE PIC X(32).
01 WS-EVENT-SEEN-TABLE.
   05 WS-EV OCCURS 400 TIMES PIC X(32).
01 WS-COMM-EVENT-TABLE.
   05 WS-CE OCCURS 400 TIMES PIC X(32).
01 WS-COMM-INST-TABLE.
   05 WS-CI OCCURS 400 TIMES PIC X(80).
01 WS-TOKEN-TABLE.
   05 WS-TK OCCURS 400 TIMES.
      10 WS-TK-TOKEN PIC X(32).
      10 WS-TK-MEM PIC X(32).
      10 WS-TK-CONFLICT PIC X VALUE "N".
01 WS-LED-TABLE.
   05 WS-LG OCCURS 400 TIMES.
      10 WS-LG-INST PIC X(80).
      10 WS-LG-CLAIM PIC X(32).
      10 WS-LG-EVENT PIC X(32).
      10 WS-LG-RAIL PIC X(8).
      10 WS-LG-AMT PIC 9(12).
      10 WS-LG-STAT PIC X(16).
01 WS-DEC-TABLE.
   05 WS-DC OCCURS 400 TIMES.
      10 WS-DC-CLAIM PIC X(32).
      10 WS-DC-EVENT PIC X(32).
      10 WS-DC-POL PIC X(32).
      10 WS-DC-AMT PIC 9(12).
      10 WS-DC-DEC PIC X(32).
      10 WS-DC-REASON PIC X(32).
      10 WS-DC-INST PIC X(80).
01 WS-REJ-TABLE.
   05 WS-RJ OCCURS 400 TIMES.
      10 WS-RJ-CLAIM PIC X(32).
      10 WS-RJ-EVENT PIC X(32).
      10 WS-RJ-CODE PIC X(32).
01 WS-REV-TABLE.
   05 WS-RV OCCURS 400 TIMES.
      10 WS-RV-CLAIM PIC X(32).
      10 WS-RV-EVENT PIC X(32).
      10 WS-RV-CODE PIC X(32).
      10 WS-RV-AMT PIC 9(12).
      10 WS-RV-SEEN PIC X VALUE "N".
01 WS-CHK-TABLE.
   05 WS-CQ OCCURS 400 TIMES.
      10 WS-CQ-INST PIC X(80).
      10 WS-CQ-CLAIM PIC X(32).
      10 WS-CQ-EVENT PIC X(32).
      10 WS-CQ-PAYEE PIC X(16).
      10 WS-CQ-AMT PIC 9(12).
      10 WS-CQ-PRI PIC X(16).
      10 WS-CQ-SEEN PIC X VALUE "N".
01 WS-EFT-TABLE.
   05 WS-EQ OCCURS 400 TIMES.
      10 WS-EQ-INST PIC X(80).
      10 WS-EQ-CLAIM PIC X(32).
      10 WS-EQ-EVENT PIC X(32).
      10 WS-EQ-BANK PIC X(32).
      10 WS-EQ-AMT PIC 9(12).
      10 WS-EQ-SEEN PIC X VALUE "N".
01 WS-VER-TABLE.
   05 WS-VQ OCCURS 400 TIMES.
      10 WS-VQ-INST PIC X(80).
      10 WS-VQ-CLAIM PIC X(32).
      10 WS-VQ-EVENT PIC X(32).
      10 WS-VQ-BANK PIC X(32).
      10 WS-VQ-AMT PIC 9(12).
      10 WS-VQ-CODE PIC X(32).
      10 WS-VQ-SEEN PIC X VALUE "N".
01 WS-CTL-COUNTS.
   05 WS-CTL-PQ-C PIC 9(8) VALUE 0.
   05 WS-CTL-PQ-A PIC 9(12) VALUE 0.
   05 WS-CTL-MR-C PIC 9(8) VALUE 0.
   05 WS-CTL-MR-A PIC 9(12) VALUE 0.
   05 WS-CTL-RJ-C PIC 9(8) VALUE 0.
   05 WS-CTL-RJ-A PIC 9(12) VALUE 0.
   05 WS-CTL-CQ-C PIC 9(8) VALUE 0.
   05 WS-CTL-CQ-A PIC 9(12) VALUE 0.
   05 WS-CTL-EQ-C PIC 9(8) VALUE 0.
   05 WS-CTL-EQ-A PIC 9(12) VALUE 0.
   05 WS-CTL-BV-C PIC 9(8) VALUE 0.
   05 WS-CTL-BV-A PIC 9(12) VALUE 0.
   05 WS-CTL-LG-C PIC 9(8) VALUE 0.
   05 WS-CTL-LG-A PIC 9(12) VALUE 0.
PROCEDURE DIVISION.
MAIN-PARA.
    CALL "SYSTEM" USING "mkdir -p /app/out"
    PERFORM READ-ABEND-ENV
    PERFORM LOAD-POLICIES
    PERFORM LOAD-DIAGNOSES
    PERFORM LOAD-FACILITIES
    PERFORM LOAD-POLICY-DECK
    PERFORM LOAD-REJECT-PREC
    PERFORM LOAD-REVIEW-PREC
    PERFORM LOAD-BANK-RESPONSES
    PERFORM LOAD-CLAIMS
    PERFORM BUILD-IDENTITY-CONFLICTS
    PERFORM LOAD-EXISTING-LEDGER
    PERFORM LOAD-OUTPUT-QUEUES
    PERFORM PROCESS-ALL-CLAIMS
    PERFORM WRITE-ALL-OUTPUTS
    PERFORM WRITE-EMPTY-CHECKPOINT
    STOP RUN.

READ-ABEND-ENV.
    MOVE SPACES TO WS-ENV
    ACCEPT WS-ENV FROM ENVIRONMENT "ABEND_AFTER_COMMITS"
    MOVE FUNCTION TRIM(WS-ENV) TO WS-TRIM
    IF WS-TRIM NOT = SPACES
        MOVE "Y" TO WS-ABEND-SET
        COMPUTE WS-ABEND-LIMIT = FUNCTION NUMVAL-C(WS-TRIM)
    END-IF.

LOAD-POLICIES.
    MOVE 0 TO WS-POL-COUNT
    OPEN INPUT POLICIES-FILE
    IF WS-FS = "35" EXIT PARAGRAPH END-IF
    MOVE "N" TO WS-EOF
    PERFORM UNTIL WS-EOF = "Y"
        READ POLICIES-FILE AT END MOVE "Y" TO WS-EOF
        NOT AT END
            IF POLICY-LINE(1:9) NOT = "policy_id"
                ADD 1 TO WS-POL-COUNT
                PERFORM PARSE-POL-LINE
            END-IF
        END-READ
    END-PERFORM
    CLOSE POLICIES-FILE.

PARSE-POL-LINE.
    MOVE SPACES TO WS-F1 WS-F2 WS-F3 WS-F4 WS-F5 WS-F6
    UNSTRING POLICY-LINE DELIMITED BY "|"
        INTO WS-F1 WS-F2 WS-F3 WS-F4 WS-F5 WS-F6
    END-UNSTRING
    MOVE WS-F1 TO WS-PL-ID(WS-POL-COUNT)
    MOVE WS-F2 TO WS-PL-MEM(WS-POL-COUNT)
    MOVE WS-F3 TO WS-PL-STAT(WS-POL-COUNT).

LOAD-DIAGNOSES.
    MOVE 0 TO WS-DX-COUNT
    OPEN INPUT DIAG-FILE
    IF WS-FS = "35" EXIT PARAGRAPH END-IF
    MOVE "N" TO WS-EOF
    PERFORM UNTIL WS-EOF = "Y"
        READ DIAG-FILE AT END MOVE "Y" TO WS-EOF
        NOT AT END
            IF DIAG-LINE(1:14) NOT = "diagnosis_code"
                ADD 1 TO WS-DX-COUNT
                MOVE SPACES TO WS-F1 WS-F2 WS-F3 WS-F4
                UNSTRING DIAG-LINE DELIMITED BY "|" INTO WS-F1 WS-F2 WS-F3 WS-F4 END-UNSTRING
                MOVE WS-F1 TO WS-DX-CODE(WS-DX-COUNT)
                MOVE WS-F2 TO WS-DX-CAT(WS-DX-COUNT)
                MOVE WS-F3 TO WS-DX-AUTH(WS-DX-COUNT)
                MOVE WS-F4 TO WS-DX-EXP(WS-DX-COUNT)
            END-IF
        END-READ
    END-PERFORM
    CLOSE DIAG-FILE.

LOAD-FACILITIES.
    MOVE 0 TO WS-FAC-COUNT
    OPEN INPUT FAC-FILE
    IF WS-FS = "35" EXIT PARAGRAPH END-IF
    MOVE "N" TO WS-EOF
    PERFORM UNTIL WS-EOF = "Y"
        READ FAC-FILE AT END MOVE "Y" TO WS-EOF
        NOT AT END
            IF FAC-LINE(1:11) NOT = "facility_id"
                ADD 1 TO WS-FAC-COUNT
                MOVE SPACES TO WS-F1 WS-F2 WS-F3 WS-F4
                UNSTRING FAC-LINE DELIMITED BY "|" INTO WS-F1 WS-F2 WS-F3 WS-F4 END-UNSTRING
                MOVE WS-F1 TO WS-FC-ID(WS-FAC-COUNT)
                MOVE WS-F2 TO WS-FC-TIER(WS-FAC-COUNT)
                MOVE WS-F3 TO WS-FC-SANC(WS-FAC-COUNT)
                MOVE WS-F4 TO WS-FC-EMER(WS-FAC-COUNT)
            END-IF
        END-READ
    END-PERFORM
    CLOSE FAC-FILE.

LOAD-POLICY-DECK.
    OPEN INPUT DECK-FILE
    IF WS-FS = "35" EXIT PARAGRAPH END-IF
    MOVE "N" TO WS-EOF
    PERFORM UNTIL WS-EOF = "Y"
        READ DECK-FILE AT END MOVE "Y" TO WS-EOF
        NOT AT END
            IF DECK-LINE(1:3) = "DCL"
                PERFORM PARSE-DECK-LINE
            END-IF
        END-READ
    END-PERFORM
    CLOSE DECK-FILE.

PARSE-DECK-LINE.
    IF DECK-LINE(1:31) = "DCL EXPEDITED_CHECK_LIMIT_CENTS"
        PERFORM EXTRACT-INIT-VAL
        COMPUTE WS-EXP-LIMIT = FUNCTION NUMVAL-C(WS-INIT-VAL)
    END-IF
    IF DECK-LINE(1:24) = "DCL EFT_BANK_VERIFY_CENTS"
        PERFORM EXTRACT-INIT-VAL
        COMPUTE WS-EFT-LIMIT = FUNCTION NUMVAL-C(WS-INIT-VAL)
    END-IF
    IF DECK-LINE(1:26) = "DCL MANUAL_REVIEW_LIMIT_CENTS"
        PERFORM EXTRACT-INIT-VAL
        COMPUTE WS-MAN-LIMIT = FUNCTION NUMVAL-C(WS-INIT-VAL)
    END-IF.

EXTRACT-INIT-VAL.
    MOVE SPACES TO WS-INIT-VAL
    MOVE 0 TO WS-INIT-START
    PERFORM VARYING WS-IDX FROM 1 BY 1 UNTIL WS-IDX > 240
        IF DECK-LINE(WS-IDX:5) = "INIT("
            MOVE WS-IDX TO WS-INIT-START
            EXIT PERFORM
        END-IF
    END-PERFORM
    IF WS-INIT-START = 0 EXIT PARAGRAPH END-IF
    COMPUTE WS-INIT-START = WS-INIT-START + 5
    PERFORM VARYING WS-JDX FROM WS-INIT-START BY 1 UNTIL WS-JDX > 250
        IF DECK-LINE(WS-JDX:1) = ")"
            EXIT PERFORM
        END-IF
        IF DECK-LINE(WS-JDX:1) NOT = "'" AND DECK-LINE(WS-JDX:1) NOT = " "
            STRING WS-INIT-VAL DELIMITED BY SPACE
                DECK-LINE(WS-JDX:1) DELIMITED BY SIZE
                INTO WS-INIT-VAL
            END-STRING
        END-IF
    END-PERFORM.

LOAD-REJECT-PREC.
    MOVE 0 TO WS-REJ-PREC-COUNT
    OPEN INPUT REJ-PREC-FILE
    IF WS-FS = "35" EXIT PARAGRAPH END-IF
    MOVE "N" TO WS-EOF
    PERFORM UNTIL WS-EOF = "Y"
        READ REJ-PREC-FILE AT END MOVE "Y" TO WS-EOF
        NOT AT END
            IF REJ-PREC-LINE(1:4) NOT = "rank"
                ADD 1 TO WS-REJ-PREC-COUNT
                MOVE SPACES TO WS-F1 WS-F2
                UNSTRING REJ-PREC-LINE DELIMITED BY "|" INTO WS-F1 WS-F2 END-UNSTRING
                COMPUTE WS-RP-RANK(WS-REJ-PREC-COUNT) = FUNCTION NUMVAL-C(WS-F1)
                MOVE WS-F2 TO WS-RP-CODE(WS-REJ-PREC-COUNT)
            END-IF
        END-READ
    END-PERFORM
    CLOSE REJ-PREC-FILE
    PERFORM SORT-REJ-PREC.

LOAD-REVIEW-PREC.
    MOVE 0 TO WS-REV-PREC-COUNT
    OPEN INPUT REV-PREC-FILE
    IF WS-FS = "35" EXIT PARAGRAPH END-IF
    MOVE "N" TO WS-EOF
    PERFORM UNTIL WS-EOF = "Y"
        READ REV-PREC-FILE AT END MOVE "Y" TO WS-EOF
        NOT AT END
            IF REV-PREC-LINE(1:4) NOT = "rank"
                ADD 1 TO WS-REV-PREC-COUNT
                MOVE SPACES TO WS-F1 WS-F2
                UNSTRING REV-PREC-LINE DELIMITED BY "|" INTO WS-F1 WS-F2 END-UNSTRING
                COMPUTE WS-VP-RANK(WS-REV-PREC-COUNT) = FUNCTION NUMVAL-C(WS-F1)
                MOVE WS-F2 TO WS-VP-CODE(WS-REV-PREC-COUNT)
            END-IF
        END-READ
    END-PERFORM
    CLOSE REV-PREC-FILE
    PERFORM SORT-REV-PREC.

SORT-REJ-PREC.
    PERFORM VARYING WS-IDX FROM 1 BY 1 UNTIL WS-IDX >= WS-REJ-PREC-COUNT
        COMPUTE WS-JDX = WS-IDX + 1
        PERFORM UNTIL WS-JDX > WS-REJ-PREC-COUNT
            IF WS-RP-RANK(WS-JDX) < WS-RP-RANK(WS-IDX)
                MOVE WS-RP-RANK(WS-IDX) TO WS-AMT-W
                MOVE WS-RP-RANK(WS-JDX) TO WS-RP-RANK(WS-IDX)
                MOVE WS-AMT-W TO WS-RP-RANK(WS-JDX)
                MOVE WS-RP-CODE(WS-IDX) TO WS-NORM
                MOVE WS-RP-CODE(WS-JDX) TO WS-RP-CODE(WS-IDX)
                MOVE WS-NORM TO WS-RP-CODE(WS-JDX)
            END-IF
            ADD 1 TO WS-JDX
        END-PERFORM
    END-PERFORM.

SORT-REV-PREC.
    PERFORM VARYING WS-IDX FROM 1 BY 1 UNTIL WS-IDX >= WS-REV-PREC-COUNT
        COMPUTE WS-JDX = WS-IDX + 1
        PERFORM UNTIL WS-JDX > WS-REV-PREC-COUNT
            IF WS-VP-RANK(WS-JDX) < WS-VP-RANK(WS-IDX)
                MOVE WS-VP-RANK(WS-IDX) TO WS-AMT-W
                MOVE WS-VP-RANK(WS-JDX) TO WS-VP-RANK(WS-IDX)
                MOVE WS-AMT-W TO WS-VP-RANK(WS-JDX)
                MOVE WS-VP-CODE(WS-IDX) TO WS-NORM
                MOVE WS-VP-CODE(WS-JDX) TO WS-VP-CODE(WS-IDX)
                MOVE WS-NORM TO WS-VP-CODE(WS-JDX)
            END-IF
            ADD 1 TO WS-JDX
        END-PERFORM
    END-PERFORM.

LOAD-BANK-RESPONSES.
    MOVE 0 TO WS-BANK-COUNT
    OPEN INPUT BANK-FILE
    IF WS-FS = "35" EXIT PARAGRAPH END-IF
    MOVE "N" TO WS-EOF
    PERFORM UNTIL WS-EOF = "Y"
        READ BANK-FILE AT END MOVE "Y" TO WS-EOF
        NOT AT END
            IF BANK-LINE(1:8) NOT = "claim_id"
                ADD 1 TO WS-BANK-COUNT
                MOVE SPACES TO WS-F1 WS-F2 WS-F3 WS-F4 WS-F5
                UNSTRING BANK-LINE DELIMITED BY "|"
                    INTO WS-F1 WS-F2 WS-F3 WS-F4 WS-F5
                END-UNSTRING
                MOVE WS-F1 TO WS-BK-CLAIM(WS-BANK-COUNT)
                MOVE WS-F2 TO WS-BK-EVENT(WS-BANK-COUNT)
                MOVE WS-F3 TO WS-BK-ACCT(WS-BANK-COUNT)
                MOVE WS-F4 TO WS-TRIM
                PERFORM NORM-TRIM-TO-NORM
                MOVE WS-NORM TO WS-BK-STAT(WS-BANK-COUNT)
            END-IF
        END-READ
    END-PERFORM
    CLOSE BANK-FILE.

LOAD-CLAIMS.
    MOVE 0 TO WS-CLAIM-COUNT
    OPEN INPUT CLAIMS-FILE
    IF WS-FS = "35" EXIT PARAGRAPH END-IF
    MOVE "N" TO WS-EOF
    PERFORM UNTIL WS-EOF = "Y"
        READ CLAIMS-FILE AT END MOVE "Y" TO WS-EOF
        NOT AT END
            IF CLAIM-LINE(1:8) NOT = "claim_id"
                ADD 1 TO WS-CLAIM-COUNT
                PERFORM PARSE-CLAIM-LINE
            END-IF
        END-READ
    END-PERFORM
    CLOSE CLAIMS-FILE.

PARSE-CLAIM-LINE.
    MOVE SPACES TO WS-F1 WS-F2 WS-F3 WS-F4 WS-F5 WS-F6 WS-F7 WS-F8
        WS-F9 WS-F10 WS-F11 WS-F12 WS-F13 WS-F14
    UNSTRING CLAIM-LINE DELIMITED BY "|"
        INTO WS-F1 WS-F2 WS-F3 WS-F4 WS-F5 WS-F6 WS-F7
             WS-F8 WS-F9 WS-F10 WS-F11 WS-F12 WS-F13 WS-F14
    END-UNSTRING
    IF WS-F1 = "claim_id" EXIT PARAGRAPH END-IF
    MOVE WS-F1 TO WS-CL-CLAIM(WS-CLAIM-COUNT)
    MOVE WS-F2 TO WS-CL-EVENT(WS-CLAIM-COUNT)
    MOVE WS-F3 TO WS-CL-POL(WS-CLAIM-COUNT)
    MOVE WS-F4 TO WS-CL-MEM(WS-CLAIM-COUNT)
    MOVE WS-F5 TO WS-CL-FAC(WS-CLAIM-COUNT)
    MOVE WS-F6 TO WS-CL-DX(WS-CLAIM-COUNT)
    COMPUTE WS-CL-AMT(WS-CLAIM-COUNT) = FUNCTION NUMVAL-C(WS-F7)
    MOVE WS-F8 TO WS-CL-PAYEE(WS-CLAIM-COUNT)
    MOVE WS-F9 TO WS-CL-BANK(WS-CLAIM-COUNT)
    MOVE WS-F10 TO WS-CL-TOKEN(WS-CLAIM-COUNT)
    MOVE WS-F11 TO WS-CL-ADJ(WS-CLAIM-COUNT)
    MOVE WS-F12 TO WS-CL-AUTH(WS-CLAIM-COUNT).

BUILD-IDENTITY-CONFLICTS.
    IF WS-STAGE < 3 EXIT PARAGRAPH END-IF
    MOVE 0 TO WS-TOKEN-COUNT
    PERFORM VARYING WS-IDX FROM 1 BY 1 UNTIL WS-IDX > WS-CLAIM-COUNT
        MOVE WS-CL-TOKEN(WS-IDX) TO WS-TRIM
        PERFORM NORM-TRIM-TO-NORM
        IF WS-NORM NOT = SPACES
            IF WS-NORM NOT = "CONFLICT"
                AND WS-NORM NOT = "MISMATCH"
                AND WS-NORM NOT = "DUPLICATE_IDENTITY"
                MOVE 0 TO WS-FOUND
                PERFORM VARYING WS-JDX FROM 1 BY 1
                    UNTIL WS-JDX > WS-TOKEN-COUNT OR WS-FOUND > 0
                    IF WS-TK-TOKEN(WS-JDX) = WS-NORM
                        MOVE WS-JDX TO WS-FOUND
                    END-IF
                END-PERFORM
                IF WS-FOUND = 0
                    ADD 1 TO WS-TOKEN-COUNT
                    MOVE WS-NORM TO WS-TK-TOKEN(WS-TOKEN-COUNT)
                    MOVE WS-CL-MEM(WS-IDX) TO WS-TK-MEM(WS-TOKEN-COUNT)
                ELSE
                    IF WS-TK-MEM(WS-FOUND) NOT = WS-CL-MEM(WS-IDX)
                        MOVE "Y" TO WS-TK-CONFLICT(WS-FOUND)
                    END-IF
                END-IF
            END-IF
        END-IF
    END-PERFORM.

LOAD-EXISTING-LEDGER.
    MOVE 0 TO WS-COMM-EVENT-COUNT
    MOVE 0 TO WS-COMM-INST-COUNT
    MOVE 0 TO WS-LED-COUNT
    PERFORM LOAD-PRIOR-FOR-COMMITTED
    IF WS-STAGE >= 4
        PERFORM LOAD-OUT-LEDGER
    END-IF.

LOAD-PRIOR-FOR-COMMITTED.
    OPEN INPUT PRIOR-LED-FILE
    IF WS-FS = "35" EXIT PARAGRAPH END-IF
    MOVE "N" TO WS-EOF
    PERFORM UNTIL WS-EOF = "Y"
        READ PRIOR-LED-FILE AT END MOVE "Y" TO WS-EOF
        NOT AT END
            IF PRIOR-LED-LINE(1:14) NOT = "instruction_id"
                MOVE PRIOR-LED-LINE TO WS-LINE-BUF
                PERFORM PARSE-COMM-LINE
            END-IF
        END-READ
    END-PERFORM
    CLOSE PRIOR-LED-FILE.

LOAD-OUT-LEDGER.
    OPEN INPUT OUT-LED-FILE
    IF WS-FS = "35" EXIT PARAGRAPH END-IF
    MOVE "N" TO WS-EOF
    PERFORM UNTIL WS-EOF = "Y"
        READ OUT-LED-FILE AT END MOVE "Y" TO WS-EOF
        NOT AT END
            IF OUT-LED-LINE(1:14) NOT = "instruction_id"
                MOVE OUT-LED-LINE TO WS-LINE-BUF
                PERFORM PARSE-LED-LINE
                PERFORM PARSE-COMM-LINE
            END-IF
        END-READ
    END-PERFORM
    CLOSE OUT-LED-FILE.

PARSE-COMM-LINE.
    MOVE SPACES TO WS-F1 WS-F2 WS-F3 WS-F4 WS-F5 WS-F6
    UNSTRING WS-LINE-BUF DELIMITED BY "|"
        INTO WS-F1 WS-F2 WS-F3 WS-F4 WS-F5 WS-F6
    END-UNSTRING
    IF WS-F1 = SPACES EXIT PARAGRAPH END-IF
    IF WS-F1 = "instruction_id" EXIT PARAGRAPH END-IF
    MOVE WS-F3 TO WS-NORM
    PERFORM ADD-COMM-EVENT-NORM
    MOVE WS-F1 TO WS-NORM
    PERFORM ADD-COMM-INST-NORM.

ADD-COMM-EVENT-NORM.
    PERFORM VARYING WS-JDX FROM 1 BY 1 UNTIL WS-JDX > WS-COMM-EVENT-COUNT
        IF WS-CE(WS-JDX) = WS-NORM EXIT PARAGRAPH END-IF
    END-PERFORM
    ADD 1 TO WS-COMM-EVENT-COUNT
    MOVE WS-NORM TO WS-CE(WS-COMM-EVENT-COUNT).

ADD-COMM-INST-NORM.
    PERFORM VARYING WS-JDX FROM 1 BY 1 UNTIL WS-JDX > WS-COMM-INST-COUNT
        IF WS-CI(WS-JDX) = WS-NORM EXIT PARAGRAPH END-IF
    END-PERFORM
    ADD 1 TO WS-COMM-INST-COUNT
    MOVE WS-NORM TO WS-CI(WS-COMM-INST-COUNT).

PARSE-LED-LINE.
    MOVE SPACES TO WS-F1 WS-F2 WS-F3 WS-F4 WS-F5 WS-F6
    UNSTRING WS-LINE-BUF DELIMITED BY "|"
        INTO WS-F1 WS-F2 WS-F3 WS-F4 WS-F5 WS-F6
    END-UNSTRING
    IF WS-F1 = SPACES EXIT PARAGRAPH END-IF
    IF WS-F1 = "instruction_id" EXIT PARAGRAPH END-IF
    MOVE 0 TO WS-FOUND
    PERFORM VARYING WS-JDX FROM 1 BY 1 UNTIL WS-JDX > WS-LED-COUNT OR WS-FOUND > 0
        IF WS-LG-INST(WS-JDX) = WS-F1
            MOVE WS-JDX TO WS-FOUND
        END-IF
    END-PERFORM
    IF WS-FOUND > 0 EXIT PARAGRAPH END-IF
    ADD 1 TO WS-LED-COUNT
    MOVE WS-F1 TO WS-LG-INST(WS-LED-COUNT)
    MOVE WS-F2 TO WS-LG-CLAIM(WS-LED-COUNT)
    MOVE WS-F3 TO WS-LG-EVENT(WS-LED-COUNT)
    MOVE WS-F4 TO WS-LG-RAIL(WS-LED-COUNT)
    COMPUTE WS-LG-AMT(WS-LED-COUNT) = FUNCTION NUMVAL-C(WS-F5)
    MOVE WS-F6 TO WS-LG-STAT(WS-LED-COUNT).

LOAD-OUTPUT-QUEUES.
    IF WS-STAGE < 4 EXIT PARAGRAPH END-IF
    PERFORM LOAD-CHECK-QUEUE
    PERFORM LOAD-EFT-QUEUE
    PERFORM LOAD-VERIFY-QUEUE
    PERFORM LOAD-REVIEW-QUEUE.

LOAD-CHECK-QUEUE.
    OPEN INPUT CHECKS-FILE
    IF WS-FS = "35" EXIT PARAGRAPH END-IF
    MOVE "N" TO WS-EOF
    PERFORM UNTIL WS-EOF = "Y"
        READ CHECKS-FILE AT END MOVE "Y" TO WS-EOF
        NOT AT END
            IF CHECK-OUT(1:14) NOT = "instruction_id"
                ADD 1 TO WS-CHK-COUNT
                MOVE SPACES TO WS-F1 WS-F2 WS-F3 WS-F4 WS-F5 WS-F6
                UNSTRING CHECK-OUT DELIMITED BY "|"
                    INTO WS-F1 WS-F2 WS-F3 WS-F4 WS-F5 WS-F6
                END-UNSTRING
                MOVE WS-F1 TO WS-CQ-INST(WS-CHK-COUNT)
                MOVE WS-F2 TO WS-CQ-CLAIM(WS-CHK-COUNT)
                MOVE WS-F3 TO WS-CQ-EVENT(WS-CHK-COUNT)
                MOVE WS-F4 TO WS-CQ-PAYEE(WS-CHK-COUNT)
                COMPUTE WS-CQ-AMT(WS-CHK-COUNT) = FUNCTION NUMVAL-C(WS-F5)
                MOVE WS-F6 TO WS-CQ-PRI(WS-CHK-COUNT)
                MOVE "Y" TO WS-CQ-SEEN(WS-CHK-COUNT)
            END-IF
        END-READ
    END-PERFORM
    CLOSE CHECKS-FILE.

LOAD-EFT-QUEUE.
    OPEN INPUT EFT-FILE
    IF WS-FS = "35" EXIT PARAGRAPH END-IF
    MOVE "N" TO WS-EOF
    PERFORM UNTIL WS-EOF = "Y"
        READ EFT-FILE AT END MOVE "Y" TO WS-EOF
        NOT AT END
            IF EFT-OUT(1:14) NOT = "instruction_id"
                ADD 1 TO WS-EFT-COUNT
                MOVE SPACES TO WS-F1 WS-F2 WS-F3 WS-F4 WS-F5
                UNSTRING EFT-OUT DELIMITED BY "|"
                    INTO WS-F1 WS-F2 WS-F3 WS-F4 WS-F5
                END-UNSTRING
                MOVE WS-F1 TO WS-EQ-INST(WS-EFT-COUNT)
                MOVE WS-F2 TO WS-EQ-CLAIM(WS-EFT-COUNT)
                MOVE WS-F3 TO WS-EQ-EVENT(WS-EFT-COUNT)
                MOVE WS-F4 TO WS-EQ-BANK(WS-EFT-COUNT)
                COMPUTE WS-EQ-AMT(WS-EFT-COUNT) = FUNCTION NUMVAL-C(WS-F5)
                MOVE "Y" TO WS-EQ-SEEN(WS-EFT-COUNT)
            END-IF
        END-READ
    END-PERFORM
    CLOSE EFT-FILE.

LOAD-VERIFY-QUEUE.
    OPEN INPUT VERIFY-FILE
    IF WS-FS = "35" EXIT PARAGRAPH END-IF
    MOVE "N" TO WS-EOF
    PERFORM UNTIL WS-EOF = "Y"
        READ VERIFY-FILE AT END MOVE "Y" TO WS-EOF
        NOT AT END
            IF VERIFY-OUT(1:14) NOT = "instruction_id"
                ADD 1 TO WS-VER-COUNT
                MOVE SPACES TO WS-F1 WS-F2 WS-F3 WS-F4 WS-F5 WS-F6
                UNSTRING VERIFY-OUT DELIMITED BY "|"
                    INTO WS-F1 WS-F2 WS-F3 WS-F4 WS-F5 WS-F6
                END-UNSTRING
                MOVE WS-F1 TO WS-VQ-INST(WS-VER-COUNT)
                MOVE WS-F2 TO WS-VQ-CLAIM(WS-VER-COUNT)
                MOVE WS-F3 TO WS-VQ-EVENT(WS-VER-COUNT)
                MOVE WS-F4 TO WS-VQ-BANK(WS-VER-COUNT)
                COMPUTE WS-VQ-AMT(WS-VER-COUNT) = FUNCTION NUMVAL-C(WS-F5)
                MOVE WS-F6 TO WS-VQ-CODE(WS-VER-COUNT)
                MOVE "Y" TO WS-VQ-SEEN(WS-VER-COUNT)
            END-IF
        END-READ
    END-PERFORM
    CLOSE VERIFY-FILE.

LOAD-REVIEW-QUEUE.
    OPEN INPUT REVIEWS-FILE
    IF WS-FS = "35" EXIT PARAGRAPH END-IF
    MOVE "N" TO WS-EOF
    PERFORM UNTIL WS-EOF = "Y"
        READ REVIEWS-FILE AT END MOVE "Y" TO WS-EOF
        NOT AT END
            IF REVIEW-OUT(1:8) NOT = "claim_id"
                ADD 1 TO WS-REV-COUNT
                MOVE SPACES TO WS-F1 WS-F2 WS-F3 WS-F4 WS-F5
                UNSTRING REVIEW-OUT DELIMITED BY "|"
                    INTO WS-F1 WS-F2 WS-F3 WS-F4 WS-F5
                END-UNSTRING
                MOVE WS-F1 TO WS-RV-CLAIM(WS-REV-COUNT)
                MOVE WS-F2 TO WS-RV-EVENT(WS-REV-COUNT)
                MOVE WS-F3 TO WS-RV-CODE(WS-REV-COUNT)
                COMPUTE WS-RV-AMT(WS-REV-COUNT) = FUNCTION NUMVAL-C(WS-F4)
                MOVE "Y" TO WS-RV-SEEN(WS-REV-COUNT)
            END-IF
        END-READ
    END-PERFORM
    CLOSE REVIEWS-FILE.

PROCESS-ALL-CLAIMS.
    PERFORM VARYING WS-CUR FROM 1 BY 1 UNTIL WS-CUR > WS-CLAIM-COUNT
        PERFORM PROCESS-ONE-CLAIM
    END-PERFORM.

PROCESS-ONE-CLAIM.
    MOVE WS-CUR TO WS-IDX
    PERFORM BUILD-INSTRUCTION-ID
    IF WS-STAGE >= 4
        PERFORM CHECK-ALREADY-COMMITTED
        IF WS-R-FLAG = "Y"
            PERFORM RECORD-EVENT-SEEN
            EXIT PARAGRAPH
        END-IF
    END-IF
    PERFORM EVALUATE-REJECT
    PERFORM RECORD-EVENT-SEEN
    IF WS-REJECT-CODE NOT = SPACES
        PERFORM ADD-REJECT-DECISION
        EXIT PARAGRAPH
    END-IF
    IF WS-STAGE = 1
        PERFORM ADD-ELIGIBLE-DECISION
        EXIT PARAGRAPH
    END-IF
    PERFORM EVALUATE-REVIEW
    IF WS-REVIEW-CODE NOT = SPACES
        PERFORM ADD-REVIEW-DECISION
        EXIT PARAGRAPH
    END-IF
    PERFORM DETERMINE-RAIL-PRIORITY
    PERFORM ADD-QUEUED-DECISION
    IF WS-STAGE >= 3
        PERFORM MAYBE-COMMIT-PAYMENT
    ELSE
        PERFORM QUEUE-PAYMENT-STAGE2
    END-IF.

BUILD-INSTRUCTION-ID.
    MOVE SPACES TO WS-INST
    STRING "PAY-" DELIMITED BY SIZE
        WS-CL-CLAIM(WS-CUR) DELIMITED BY SPACE
        "-" DELIMITED BY SIZE
        WS-CL-EVENT(WS-CUR) DELIMITED BY SPACE
        INTO WS-INST
    END-STRING.

CHECK-ALREADY-COMMITTED.
    MOVE "N" TO WS-R-FLAG
    PERFORM VARYING WS-JDX FROM 1 BY 1 UNTIL WS-JDX > WS-COMM-EVENT-COUNT
        IF WS-CE(WS-JDX) = WS-CL-EVENT(WS-CUR)
            MOVE "Y" TO WS-R-FLAG
            EXIT PERFORM
        END-IF
    END-PERFORM
    IF WS-R-FLAG NOT = "Y"
        PERFORM VARYING WS-JDX FROM 1 BY 1 UNTIL WS-JDX > WS-COMM-INST-COUNT
            IF WS-CI(WS-JDX) = WS-INST
                MOVE "Y" TO WS-R-FLAG
                EXIT PERFORM
            END-IF
        END-PERFORM
    END-IF
    IF WS-R-FLAG = "Y"
        PERFORM ADD-ALREADY-COMMITTED
    END-IF.

ADD-ALREADY-COMMITTED.
    ADD 1 TO WS-DEC-COUNT
    MOVE WS-CL-CLAIM(WS-CUR) TO WS-DC-CLAIM(WS-DEC-COUNT)
    MOVE WS-CL-EVENT(WS-CUR) TO WS-DC-EVENT(WS-DEC-COUNT)
    MOVE WS-CL-POL(WS-CUR) TO WS-DC-POL(WS-DEC-COUNT)
    MOVE WS-CL-AMT(WS-CUR) TO WS-DC-AMT(WS-DEC-COUNT)
    MOVE "ALREADY_COMMITTED" TO WS-DC-DEC(WS-DEC-COUNT)
    MOVE "DUPLICATE_EVENT" TO WS-DC-REASON(WS-DEC-COUNT)
    MOVE WS-INST TO WS-DC-INST(WS-DEC-COUNT).

RECORD-EVENT-SEEN.
    MOVE WS-CL-EVENT(WS-CUR) TO WS-NORM
    PERFORM VARYING WS-JDX FROM 1 BY 1 UNTIL WS-JDX > WS-EVENT-COUNT
        IF WS-EV(WS-JDX) = WS-NORM EXIT PARAGRAPH END-IF
    END-PERFORM
    ADD 1 TO WS-EVENT-COUNT
    MOVE WS-NORM TO WS-EV(WS-EVENT-COUNT).

EVALUATE-REJECT.
    MOVE SPACES TO WS-REJECT-CODE
    MOVE "N" TO WS-RF-DUP WS-RF-NOPOL WS-RF-INACT WS-RF-MMEM
        WS-RF-NOADJ WS-RF-NOCAT WS-RF-AUTH WS-RF-AMT
    PERFORM CHECK-DUP-EVENT
    PERFORM CHECK-POLICY-REJECT
    PERFORM CHECK-ADJ-REJECT
    PERFORM CHECK-DX-REJECT
    PERFORM CHECK-AMT-REJECT
    PERFORM PICK-REJECT-CODE.

CHECK-DUP-EVENT.
    MOVE WS-CL-EVENT(WS-CUR) TO WS-NORM
    IF WS-STAGE >= 4
        PERFORM VARYING WS-JDX FROM 1 BY 1 UNTIL WS-JDX > WS-COMM-EVENT-COUNT
            IF WS-CE(WS-JDX) = WS-NORM
                MOVE "Y" TO WS-RF-DUP
                EXIT PARAGRAPH
            END-IF
        END-PERFORM
    END-IF
    PERFORM VARYING WS-JDX FROM 1 BY 1 UNTIL WS-JDX > WS-EVENT-COUNT
        IF WS-EV(WS-JDX) = WS-NORM
            MOVE "Y" TO WS-RF-DUP
            EXIT PARAGRAPH
        END-IF
    END-PERFORM.

CHECK-POLICY-REJECT.
    MOVE 0 TO WS-FOUND
    PERFORM VARYING WS-JDX FROM 1 BY 1 UNTIL WS-JDX > WS-POL-COUNT OR WS-FOUND > 0
        IF WS-PL-ID(WS-JDX) = WS-CL-POL(WS-CUR)
            MOVE WS-JDX TO WS-FOUND
        END-IF
    END-PERFORM
    IF WS-FOUND = 0
        MOVE "Y" TO WS-RF-NOPOL
        EXIT PARAGRAPH
    END-IF
    MOVE WS-PL-STAT(WS-FOUND) TO WS-TRIM
    PERFORM NORM-TRIM-TO-NORM
    IF WS-NORM NOT = "ACTIVE"
        MOVE "Y" TO WS-RF-INACT
    END-IF
    IF WS-PL-MEM(WS-FOUND) NOT = WS-CL-MEM(WS-CUR)
        MOVE "Y" TO WS-RF-MMEM
    END-IF.

CHECK-ADJ-REJECT.
    MOVE WS-CL-ADJ(WS-CUR) TO WS-TRIM
    PERFORM NORM-TRIM-TO-NORM
    IF WS-NORM NOT = "APPROVED"
        MOVE "Y" TO WS-RF-NOADJ
    END-IF.

CHECK-DX-REJECT.
    MOVE 0 TO WS-FOUND
    PERFORM VARYING WS-JDX FROM 1 BY 1 UNTIL WS-JDX > WS-DX-COUNT OR WS-FOUND > 0
        IF WS-DX-CODE(WS-JDX) = WS-CL-DX(WS-CUR)
            MOVE WS-JDX TO WS-FOUND
        END-IF
    END-PERFORM
    IF WS-FOUND = 0
        MOVE "Y" TO WS-RF-NOCAT
        EXIT PARAGRAPH
    END-IF
    MOVE WS-DX-CAT(WS-FOUND) TO WS-TRIM
    PERFORM NORM-TRIM-TO-NORM
    IF WS-NORM NOT = "Y"
        MOVE "Y" TO WS-RF-NOCAT
        EXIT PARAGRAPH
    END-IF
    MOVE WS-DX-AUTH(WS-FOUND) TO WS-TRIM
    PERFORM NORM-TRIM-TO-NORM
    IF WS-NORM = "Y"
        MOVE WS-CL-AUTH(WS-CUR) TO WS-TRIM
        PERFORM NORM-TRIM-TO-NORM
        IF WS-NORM = SPACES
            MOVE "Y" TO WS-RF-AUTH
        END-IF
    END-IF.

CHECK-AMT-REJECT.
    IF WS-CL-AMT(WS-CUR) <= 0
        MOVE "Y" TO WS-RF-AMT
    END-IF.

PICK-REJECT-CODE.
    PERFORM VARYING WS-JDX FROM 1 BY 1 UNTIL WS-JDX > WS-REJ-PREC-COUNT
        MOVE WS-RP-CODE(WS-JDX) TO WS-NORM
        IF WS-NORM = "DUPLICATE_EVENT" AND WS-RF-DUP = "Y"
            MOVE WS-NORM TO WS-REJECT-CODE EXIT PARAGRAPH
        END-IF
        IF WS-NORM = "POLICY_NOT_FOUND" AND WS-RF-NOPOL = "Y"
            MOVE WS-NORM TO WS-REJECT-CODE EXIT PARAGRAPH
        END-IF
        IF WS-NORM = "POLICY_INACTIVE" AND WS-RF-INACT = "Y"
            MOVE WS-NORM TO WS-REJECT-CODE EXIT PARAGRAPH
        END-IF
        IF WS-NORM = "MEMBER_MISMATCH" AND WS-RF-MMEM = "Y"
            MOVE WS-NORM TO WS-REJECT-CODE EXIT PARAGRAPH
        END-IF
        IF WS-NORM = "ADJUDICATION_NOT_APPROVED" AND WS-RF-NOADJ = "Y"
            MOVE WS-NORM TO WS-REJECT-CODE EXIT PARAGRAPH
        END-IF
        IF WS-NORM = "NON_CATASTROPHIC" AND WS-RF-NOCAT = "Y"
            MOVE WS-NORM TO WS-REJECT-CODE EXIT PARAGRAPH
        END-IF
        IF WS-NORM = "AUTH_REQUIRED" AND WS-RF-AUTH = "Y"
            MOVE WS-NORM TO WS-REJECT-CODE EXIT PARAGRAPH
        END-IF
        IF WS-NORM = "AMOUNT_INVALID" AND WS-RF-AMT = "Y"
            MOVE WS-NORM TO WS-REJECT-CODE EXIT PARAGRAPH
        END-IF
    END-PERFORM.

ADD-REJECT-DECISION.
    ADD 1 TO WS-DEC-COUNT
    MOVE WS-CL-CLAIM(WS-CUR) TO WS-DC-CLAIM(WS-DEC-COUNT)
    MOVE WS-CL-EVENT(WS-CUR) TO WS-DC-EVENT(WS-DEC-COUNT)
    MOVE WS-CL-POL(WS-CUR) TO WS-DC-POL(WS-DEC-COUNT)
    MOVE WS-CL-AMT(WS-CUR) TO WS-DC-AMT(WS-DEC-COUNT)
    MOVE "REJECT" TO WS-DC-DEC(WS-DEC-COUNT)
    MOVE WS-REJECT-CODE TO WS-DC-REASON(WS-DEC-COUNT)
    MOVE SPACES TO WS-DC-INST(WS-DEC-COUNT)
    ADD 1 TO WS-REJ-COUNT
    MOVE WS-CL-CLAIM(WS-CUR) TO WS-RJ-CLAIM(WS-REJ-COUNT)
    MOVE WS-CL-EVENT(WS-CUR) TO WS-RJ-EVENT(WS-REJ-COUNT)
    MOVE WS-REJECT-CODE TO WS-RJ-CODE(WS-REJ-COUNT).

ADD-ELIGIBLE-DECISION.
    ADD 1 TO WS-DEC-COUNT
    MOVE WS-CL-CLAIM(WS-CUR) TO WS-DC-CLAIM(WS-DEC-COUNT)
    MOVE WS-CL-EVENT(WS-CUR) TO WS-DC-EVENT(WS-DEC-COUNT)
    MOVE WS-CL-POL(WS-CUR) TO WS-DC-POL(WS-DEC-COUNT)
    MOVE WS-CL-AMT(WS-CUR) TO WS-DC-AMT(WS-DEC-COUNT)
    MOVE "ELIGIBLE_PENDING_ROUTE" TO WS-DC-DEC(WS-DEC-COUNT)
    MOVE "ELIGIBLE" TO WS-DC-REASON(WS-DEC-COUNT)
    MOVE SPACES TO WS-DC-INST(WS-DEC-COUNT).

EVALUATE-REVIEW.
    MOVE SPACES TO WS-REVIEW-CODE
    MOVE "N" TO WS-VF-ID WS-VF-SANC WS-VF-NTR WS-VF-BANK WS-VF-MAN
    IF WS-STAGE >= 2
        PERFORM CHECK-IDENTITY-REVIEW
        PERFORM CHECK-FACILITY-REVIEW
    END-IF
    IF WS-STAGE >= 3
        PERFORM CHECK-BANK-REVIEW
        IF WS-CL-AMT(WS-CUR) >= WS-MAN-LIMIT
            MOVE "Y" TO WS-VF-MAN
        END-IF
    END-IF
    PERFORM PICK-REVIEW-CODE.

CHECK-IDENTITY-REVIEW.
    MOVE WS-CL-TOKEN(WS-CUR) TO WS-TRIM
    PERFORM NORM-TRIM-TO-NORM
    IF WS-NORM = "CONFLICT" OR WS-NORM = "MISMATCH"
        OR WS-NORM = "DUPLICATE_IDENTITY"
        MOVE "Y" TO WS-VF-ID
        EXIT PARAGRAPH
    END-IF
    PERFORM VARYING WS-JDX FROM 1 BY 1 UNTIL WS-JDX > WS-TOKEN-COUNT
        IF WS-TK-TOKEN(WS-JDX) = WS-NORM AND WS-TK-CONFLICT(WS-JDX) = "Y"
            MOVE "Y" TO WS-VF-ID
            EXIT PARAGRAPH
        END-IF
    END-PERFORM.

CHECK-FACILITY-REVIEW.
    MOVE 0 TO WS-FOUND
    PERFORM VARYING WS-JDX FROM 1 BY 1 UNTIL WS-JDX > WS-FAC-COUNT OR WS-FOUND > 0
        IF WS-FC-ID(WS-JDX) = WS-CL-FAC(WS-CUR)
            MOVE WS-JDX TO WS-FOUND
        END-IF
    END-PERFORM
    IF WS-FOUND = 0
        MOVE "Y" TO WS-VF-NTR
        EXIT PARAGRAPH
    END-IF
    MOVE WS-FC-SANC(WS-FOUND) TO WS-TRIM
    PERFORM NORM-TRIM-TO-NORM
    IF WS-NORM = "Y"
        MOVE "Y" TO WS-VF-SANC
    END-IF
    MOVE WS-FC-TIER(WS-FOUND) TO WS-TRIM
    PERFORM NORM-TRIM-TO-NORM
    IF WS-NORM = "UNTRUSTED"
        MOVE WS-FC-EMER(WS-FOUND) TO WS-TRIM
        PERFORM NORM-TRIM-TO-NORM
        IF WS-NORM NOT = "Y"
            MOVE "Y" TO WS-VF-NTR
        END-IF
    END-IF.

CHECK-BANK-REVIEW.
    MOVE WS-CL-PAYEE(WS-CUR) TO WS-TRIM
    PERFORM NORM-TRIM-TO-NORM
    IF WS-NORM NOT = "EFT" EXIT PARAGRAPH END-IF
    IF WS-CL-AMT(WS-CUR) < WS-EFT-LIMIT EXIT PARAGRAPH END-IF
    MOVE 0 TO WS-FOUND
    PERFORM VARYING WS-JDX FROM 1 BY 1 UNTIL WS-JDX > WS-BANK-COUNT OR WS-FOUND > 0
        IF WS-BK-CLAIM(WS-JDX) = WS-CL-CLAIM(WS-CUR)
            AND WS-BK-EVENT(WS-JDX) = WS-CL-EVENT(WS-CUR)
            AND WS-BK-ACCT(WS-JDX) = WS-CL-BANK(WS-CUR)
            MOVE WS-JDX TO WS-FOUND
        END-IF
    END-PERFORM
    IF WS-FOUND = 0
        MOVE "Y" TO WS-VF-BANK
        EXIT PARAGRAPH
    END-IF
    IF WS-BK-STAT(WS-FOUND) NOT = "APPROVED"
        MOVE "Y" TO WS-VF-BANK
    END-IF.

PICK-REVIEW-CODE.
    PERFORM VARYING WS-JDX FROM 1 BY 1 UNTIL WS-JDX > WS-REV-PREC-COUNT
        MOVE WS-VP-CODE(WS-JDX) TO WS-NORM
        IF WS-NORM = "IDENTITY_CONFLICT" AND WS-VF-ID = "Y"
            MOVE WS-NORM TO WS-REVIEW-CODE EXIT PARAGRAPH
        END-IF
        IF WS-NORM = "FACILITY_SANCTIONED" AND WS-VF-SANC = "Y"
            MOVE WS-NORM TO WS-REVIEW-CODE EXIT PARAGRAPH
        END-IF
        IF WS-NORM = "FACILITY_NOT_TRUSTED" AND WS-VF-NTR = "Y"
            MOVE WS-NORM TO WS-REVIEW-CODE EXIT PARAGRAPH
        END-IF
        IF WS-NORM = "BANK_VERIFY_REQUIRED" AND WS-VF-BANK = "Y"
            MOVE WS-NORM TO WS-REVIEW-CODE EXIT PARAGRAPH
        END-IF
        IF WS-NORM = "MANUAL_LIMIT_EXCEEDED" AND WS-VF-MAN = "Y"
            MOVE WS-NORM TO WS-REVIEW-CODE EXIT PARAGRAPH
        END-IF
    END-PERFORM.

ADD-REVIEW-DECISION.
    ADD 1 TO WS-DEC-COUNT
    MOVE WS-CL-CLAIM(WS-CUR) TO WS-DC-CLAIM(WS-DEC-COUNT)
    MOVE WS-CL-EVENT(WS-CUR) TO WS-DC-EVENT(WS-DEC-COUNT)
    MOVE WS-CL-POL(WS-CUR) TO WS-DC-POL(WS-DEC-COUNT)
    MOVE WS-CL-AMT(WS-CUR) TO WS-DC-AMT(WS-DEC-COUNT)
    MOVE "MANUAL_REVIEW" TO WS-DC-DEC(WS-DEC-COUNT)
    MOVE WS-REVIEW-CODE TO WS-DC-REASON(WS-DEC-COUNT)
    MOVE SPACES TO WS-DC-INST(WS-DEC-COUNT)
    PERFORM ADD-UNIQUE-REVIEW
    IF WS-STAGE >= 3 AND WS-REVIEW-CODE = "BANK_VERIFY_REQUIRED"
        PERFORM ADD-UNIQUE-VERIFY
    END-IF.

ADD-UNIQUE-REVIEW.
    PERFORM VARYING WS-JDX FROM 1 BY 1 UNTIL WS-JDX > WS-REV-COUNT
        IF WS-RV-CLAIM(WS-JDX) = WS-CL-CLAIM(WS-CUR)
            AND WS-RV-EVENT(WS-JDX) = WS-CL-EVENT(WS-CUR)
            AND WS-RV-CODE(WS-JDX) = WS-REVIEW-CODE
            EXIT PARAGRAPH
        END-IF
    END-PERFORM
    ADD 1 TO WS-REV-COUNT
    MOVE WS-CL-CLAIM(WS-CUR) TO WS-RV-CLAIM(WS-REV-COUNT)
    MOVE WS-CL-EVENT(WS-CUR) TO WS-RV-EVENT(WS-REV-COUNT)
    MOVE WS-REVIEW-CODE TO WS-RV-CODE(WS-REV-COUNT)
    MOVE WS-CL-AMT(WS-CUR) TO WS-RV-AMT(WS-REV-COUNT)
    MOVE "Y" TO WS-RV-SEEN(WS-REV-COUNT).

ADD-UNIQUE-VERIFY.
    PERFORM VARYING WS-JDX FROM 1 BY 1 UNTIL WS-JDX > WS-VER-COUNT
        IF WS-VQ-INST(WS-JDX) = WS-INST EXIT PARAGRAPH END-IF
    END-PERFORM
    ADD 1 TO WS-VER-COUNT
    MOVE WS-INST TO WS-VQ-INST(WS-VER-COUNT)
    MOVE WS-CL-CLAIM(WS-CUR) TO WS-VQ-CLAIM(WS-VER-COUNT)
    MOVE WS-CL-EVENT(WS-CUR) TO WS-VQ-EVENT(WS-VER-COUNT)
    MOVE WS-CL-BANK(WS-CUR) TO WS-VQ-BANK(WS-VER-COUNT)
    MOVE WS-CL-AMT(WS-CUR) TO WS-VQ-AMT(WS-VER-COUNT)
    MOVE WS-REVIEW-CODE TO WS-VQ-CODE(WS-VER-COUNT)
    MOVE "Y" TO WS-VQ-SEEN(WS-VER-COUNT).

DETERMINE-RAIL-PRIORITY.
    MOVE "NORMAL" TO WS-PRIORITY
    MOVE WS-CL-PAYEE(WS-CUR) TO WS-TRIM
    PERFORM NORM-TRIM-TO-NORM
    IF WS-NORM = "EFT"
        MOVE WS-CL-BANK(WS-CUR) TO WS-TRIM
        PERFORM NORM-TRIM-TO-NORM
        IF WS-NORM NOT = SPACES
            MOVE "EFT" TO WS-RAIL
            EXIT PARAGRAPH
        END-IF
    END-IF
    MOVE "CHECK" TO WS-RAIL
    MOVE 0 TO WS-FOUND
    PERFORM VARYING WS-JDX FROM 1 BY 1 UNTIL WS-JDX > WS-DX-COUNT OR WS-FOUND > 0
        IF WS-DX-CODE(WS-JDX) = WS-CL-DX(WS-CUR)
            MOVE WS-JDX TO WS-FOUND
        END-IF
    END-PERFORM
    IF WS-RAIL NOT = "CHECK" EXIT PARAGRAPH END-IF
    IF WS-FOUND = 0 EXIT PARAGRAPH END-IF
    MOVE WS-DX-EXP(WS-FOUND) TO WS-TRIM
    PERFORM NORM-TRIM-TO-NORM
    IF WS-NORM NOT = "Y" EXIT PARAGRAPH END-IF
    IF WS-CL-AMT(WS-CUR) > WS-EXP-LIMIT EXIT PARAGRAPH END-IF
    MOVE 0 TO WS-FOUND
    PERFORM VARYING WS-JDX FROM 1 BY 1 UNTIL WS-JDX > WS-FAC-COUNT OR WS-FOUND > 0
        IF WS-FC-ID(WS-JDX) = WS-CL-FAC(WS-CUR)
            MOVE WS-JDX TO WS-FOUND
        END-IF
    END-PERFORM
    IF WS-FOUND = 0 EXIT PARAGRAPH END-IF
    MOVE WS-FC-TIER(WS-FOUND) TO WS-TRIM
    PERFORM NORM-TRIM-TO-NORM
    IF WS-NORM = "TRUSTED"
        MOVE "EXPEDITED" TO WS-PRIORITY
        EXIT PARAGRAPH
    END-IF
    MOVE WS-FC-EMER(WS-FOUND) TO WS-TRIM
    PERFORM NORM-TRIM-TO-NORM
    IF WS-NORM = "Y"
        MOVE "EXPEDITED" TO WS-PRIORITY
    END-IF.

ADD-QUEUED-DECISION.
    ADD 1 TO WS-DEC-COUNT
    MOVE WS-CL-CLAIM(WS-CUR) TO WS-DC-CLAIM(WS-DEC-COUNT)
    MOVE WS-CL-EVENT(WS-CUR) TO WS-DC-EVENT(WS-DEC-COUNT)
    MOVE WS-CL-POL(WS-CUR) TO WS-DC-POL(WS-DEC-COUNT)
    MOVE WS-CL-AMT(WS-CUR) TO WS-DC-AMT(WS-DEC-COUNT)
    MOVE "PAYMENT_QUEUED" TO WS-DC-DEC(WS-DEC-COUNT)
    MOVE WS-INST TO WS-DC-INST(WS-DEC-COUNT)
    IF WS-PRIORITY = "EXPEDITED"
        MOVE "EXPEDITED_CHECK" TO WS-DC-REASON(WS-DEC-COUNT)
    ELSE
        MOVE WS-RAIL TO WS-DC-REASON(WS-DEC-COUNT)
    END-IF.

MAYBE-COMMIT-PAYMENT.
    MOVE 0 TO WS-FOUND
    PERFORM VARYING WS-JDX FROM 1 BY 1 UNTIL WS-JDX > WS-LED-COUNT OR WS-FOUND > 0
        IF WS-LG-INST(WS-JDX) = WS-INST
            MOVE WS-JDX TO WS-FOUND
        END-IF
    END-PERFORM
    IF WS-FOUND > 0 EXIT PARAGRAPH END-IF
    ADD 1 TO WS-LED-COUNT
    MOVE WS-INST TO WS-LG-INST(WS-LED-COUNT)
    MOVE WS-CL-CLAIM(WS-CUR) TO WS-LG-CLAIM(WS-LED-COUNT)
    MOVE WS-CL-EVENT(WS-CUR) TO WS-LG-EVENT(WS-LED-COUNT)
    MOVE WS-RAIL TO WS-LG-RAIL(WS-LED-COUNT)
    MOVE WS-CL-AMT(WS-CUR) TO WS-LG-AMT(WS-LED-COUNT)
    MOVE "COMMITTED" TO WS-LG-STAT(WS-LED-COUNT)
    PERFORM ADD-COMM-EVENT-FROM-CUR
    PERFORM ADD-COMM-INST-FROM-CUR
    IF WS-RAIL = "EFT"
        PERFORM ADD-UNIQUE-EFT
    ELSE
        PERFORM ADD-UNIQUE-CHECK
    END-IF
    IF WS-STAGE >= 4
        ADD 1 TO WS-NEW-COMMITS
        PERFORM FLUSH-STAGE4-OUTPUTS
        IF WS-ABEND-SET = "Y" AND WS-NEW-COMMITS >= WS-ABEND-LIMIT
            PERFORM WRITE-ABEND-OUTPUTS
            MOVE 77 TO RETURN-CODE
            STOP RUN
        END-IF
    END-IF.

ADD-COMM-EVENT-FROM-CUR.
    MOVE WS-CL-EVENT(WS-CUR) TO WS-NORM
    PERFORM ADD-COMM-EVENT-NORM.

ADD-COMM-INST-FROM-CUR.
    MOVE WS-INST TO WS-NORM
    PERFORM ADD-COMM-INST-NORM.

QUEUE-PAYMENT-STAGE2.
    IF WS-RAIL = "EFT"
        PERFORM ADD-UNIQUE-EFT
    ELSE
        PERFORM ADD-UNIQUE-CHECK
    END-IF.

ADD-UNIQUE-CHECK.
    PERFORM VARYING WS-JDX FROM 1 BY 1 UNTIL WS-JDX > WS-CHK-COUNT
        IF WS-CQ-INST(WS-JDX) = WS-INST EXIT PARAGRAPH END-IF
    END-PERFORM
    ADD 1 TO WS-CHK-COUNT
    MOVE WS-INST TO WS-CQ-INST(WS-CHK-COUNT)
    MOVE WS-CL-CLAIM(WS-CUR) TO WS-CQ-CLAIM(WS-CHK-COUNT)
    MOVE WS-CL-EVENT(WS-CUR) TO WS-CQ-EVENT(WS-CHK-COUNT)
    MOVE WS-CL-PAYEE(WS-CUR) TO WS-CQ-PAYEE(WS-CHK-COUNT)
    MOVE WS-CL-AMT(WS-CUR) TO WS-CQ-AMT(WS-CHK-COUNT)
    MOVE WS-PRIORITY TO WS-CQ-PRI(WS-CHK-COUNT)
    MOVE "Y" TO WS-CQ-SEEN(WS-CHK-COUNT).

ADD-UNIQUE-EFT.
    PERFORM VARYING WS-JDX FROM 1 BY 1 UNTIL WS-JDX > WS-EFT-COUNT
        IF WS-EQ-INST(WS-JDX) = WS-INST EXIT PARAGRAPH END-IF
    END-PERFORM
    ADD 1 TO WS-EFT-COUNT
    MOVE WS-INST TO WS-EQ-INST(WS-EFT-COUNT)
    MOVE WS-CL-CLAIM(WS-CUR) TO WS-EQ-CLAIM(WS-EFT-COUNT)
    MOVE WS-CL-EVENT(WS-CUR) TO WS-EQ-EVENT(WS-EFT-COUNT)
    MOVE WS-CL-BANK(WS-CUR) TO WS-EQ-BANK(WS-EFT-COUNT)
    MOVE WS-CL-AMT(WS-CUR) TO WS-EQ-AMT(WS-EFT-COUNT)
    MOVE "Y" TO WS-EQ-SEEN(WS-EFT-COUNT).

FLUSH-STAGE4-OUTPUTS.
    PERFORM REWRITE-LEDGER-FILE
    PERFORM REWRITE-CHECK-FILE
    PERFORM REWRITE-EFT-FILE
    PERFORM WRITE-CHECKPOINT-LINE.

WRITE-CHECKPOINT-LINE.
    OPEN OUTPUT CHECKPOINT-FILE
    MOVE SPACES TO CHECKPOINT-OUT
    STRING "last_committed_instruction_id=" DELIMITED BY SIZE
        WS-INST DELIMITED BY SPACE
        INTO CHECKPOINT-OUT
    END-STRING
    WRITE CHECKPOINT-OUT
    MOVE SPACES TO CHECKPOINT-OUT
    STRING "last_committed_event_id=" DELIMITED BY SIZE
        WS-CL-EVENT(WS-CUR) DELIMITED BY SPACE
        INTO CHECKPOINT-OUT
    END-STRING
    WRITE CHECKPOINT-OUT
    MOVE SPACES TO CHECKPOINT-OUT
    STRING "committed_count=" DELIMITED BY SIZE
        WS-LED-COUNT DELIMITED BY SIZE
        INTO CHECKPOINT-OUT
    END-STRING
    WRITE CHECKPOINT-OUT
    CLOSE CHECKPOINT-FILE.

WRITE-ABEND-OUTPUTS.
    PERFORM REWRITE-DECISION-FILE
    PERFORM REWRITE-REJECT-FILE
    PERFORM REWRITE-REVIEW-FILE
    PERFORM REWRITE-VERIFY-FILE
    PERFORM COMPUTE-CONTROL-TOTALS
    PERFORM REWRITE-CONTROL-FILE.

WRITE-ALL-OUTPUTS.
    PERFORM REWRITE-DECISION-FILE
    PERFORM REWRITE-REJECT-FILE
    IF WS-STAGE >= 2
        PERFORM REWRITE-REVIEW-FILE
        PERFORM REWRITE-CHECK-FILE
    END-IF
    IF WS-STAGE >= 3
        PERFORM REWRITE-EFT-FILE
        PERFORM REWRITE-VERIFY-FILE
        PERFORM REWRITE-LEDGER-FILE
        PERFORM COMPUTE-CONTROL-TOTALS
        PERFORM REWRITE-CONTROL-FILE
    END-IF.

WRITE-EMPTY-CHECKPOINT.
    IF WS-STAGE < 4 EXIT PARAGRAPH END-IF
    OPEN INPUT CHECKPOINT-FILE
    IF WS-FS NOT = "35"
        CLOSE CHECKPOINT-FILE
        EXIT PARAGRAPH
    END-IF
    OPEN OUTPUT CHECKPOINT-FILE
    MOVE "last_committed_instruction_id=" TO CHECKPOINT-OUT
    WRITE CHECKPOINT-OUT
    MOVE "last_committed_event_id=" TO CHECKPOINT-OUT
    WRITE CHECKPOINT-OUT
    MOVE SPACES TO CHECKPOINT-OUT
    STRING "committed_count=" DELIMITED BY SIZE
        WS-LED-COUNT DELIMITED BY SIZE
        INTO CHECKPOINT-OUT
    END-STRING
    WRITE CHECKPOINT-OUT
    CLOSE CHECKPOINT-FILE.

REWRITE-DECISION-FILE.
    OPEN OUTPUT DECISIONS-FILE
    MOVE "claim_id|event_id|policy_id|amount_cents|decision|reason_code|instruction_id" TO DECISION-OUT
    WRITE DECISION-OUT
    PERFORM VARYING WS-IDX FROM 1 BY 1 UNTIL WS-IDX > WS-DEC-COUNT
        MOVE WS-DC-AMT(WS-IDX) TO WS-AMT-W
        PERFORM PREPARE-AMT-STR
        MOVE SPACES TO DECISION-OUT
        STRING WS-DC-CLAIM(WS-IDX) DELIMITED BY SPACE "|"
            WS-DC-EVENT(WS-IDX) DELIMITED BY SPACE "|"
            WS-DC-POL(WS-IDX) DELIMITED BY SPACE "|"
            WS-AMT-STR DELIMITED BY SPACE "|"
            WS-DC-DEC(WS-IDX) DELIMITED BY SPACE "|"
            WS-DC-REASON(WS-IDX) DELIMITED BY SPACE "|"
            WS-DC-INST(WS-IDX) DELIMITED BY SPACE
            INTO DECISION-OUT
        END-STRING
        WRITE DECISION-OUT
    END-PERFORM
    CLOSE DECISIONS-FILE.

REWRITE-REJECT-FILE.
    OPEN OUTPUT REJECTS-FILE
    MOVE "claim_id|event_id|reason_code" TO REJECT-OUT
    WRITE REJECT-OUT
    PERFORM VARYING WS-IDX FROM 1 BY 1 UNTIL WS-IDX > WS-REJ-COUNT
        MOVE SPACES TO REJECT-OUT
        STRING WS-RJ-CLAIM(WS-IDX) DELIMITED BY SPACE "|"
            WS-RJ-EVENT(WS-IDX) DELIMITED BY SPACE "|"
            WS-RJ-CODE(WS-IDX) DELIMITED BY SPACE
            INTO REJECT-OUT
        END-STRING
        WRITE REJECT-OUT
    END-PERFORM
    CLOSE REJECTS-FILE.

REWRITE-REVIEW-FILE.
    OPEN OUTPUT REVIEWS-FILE
    MOVE "claim_id|event_id|reason_code|amount_cents|required_action" TO REVIEW-OUT
    WRITE REVIEW-OUT
    PERFORM VARYING WS-IDX FROM 1 BY 1 UNTIL WS-IDX > WS-REV-COUNT
        MOVE WS-RV-AMT(WS-IDX) TO WS-AMT-W
        PERFORM PREPARE-AMT-STR
        MOVE SPACES TO REVIEW-OUT
        STRING WS-RV-CLAIM(WS-IDX) DELIMITED BY SPACE "|"
            WS-RV-EVENT(WS-IDX) DELIMITED BY SPACE "|"
            WS-RV-CODE(WS-IDX) DELIMITED BY SPACE "|"
            WS-AMT-STR DELIMITED BY SPACE "|"
            "SUPERVISOR_REVIEW" DELIMITED BY SIZE
            INTO REVIEW-OUT
        END-STRING
        WRITE REVIEW-OUT
    END-PERFORM
    CLOSE REVIEWS-FILE.

REWRITE-CHECK-FILE.
    OPEN OUTPUT CHECKS-FILE
    MOVE "instruction_id|claim_id|event_id|payee_type|amount_cents|priority" TO CHECK-OUT
    WRITE CHECK-OUT
    PERFORM VARYING WS-IDX FROM 1 BY 1 UNTIL WS-IDX > WS-CHK-COUNT
        MOVE WS-CQ-AMT(WS-IDX) TO WS-AMT-W
        PERFORM PREPARE-AMT-STR
        MOVE SPACES TO CHECK-OUT
        STRING WS-CQ-INST(WS-IDX) DELIMITED BY SPACE "|"
            WS-CQ-CLAIM(WS-IDX) DELIMITED BY SPACE "|"
            WS-CQ-EVENT(WS-IDX) DELIMITED BY SPACE "|"
            WS-CQ-PAYEE(WS-IDX) DELIMITED BY SPACE "|"
            WS-AMT-STR DELIMITED BY SIZE "|"
            WS-CQ-PRI(WS-IDX) DELIMITED BY SPACE
            INTO CHECK-OUT
        END-STRING
        WRITE CHECK-OUT
    END-PERFORM
    CLOSE CHECKS-FILE.

REWRITE-EFT-FILE.
    OPEN OUTPUT EFT-FILE
    MOVE "instruction_id|claim_id|event_id|bank_account|amount_cents" TO EFT-OUT
    WRITE EFT-OUT
    PERFORM VARYING WS-IDX FROM 1 BY 1 UNTIL WS-IDX > WS-EFT-COUNT
        MOVE WS-EQ-AMT(WS-IDX) TO WS-AMT-W
        PERFORM PREPARE-AMT-STR
        MOVE SPACES TO EFT-OUT
        STRING WS-EQ-INST(WS-IDX) DELIMITED BY SPACE "|"
            WS-EQ-CLAIM(WS-IDX) DELIMITED BY SPACE "|"
            WS-EQ-EVENT(WS-IDX) DELIMITED BY SPACE "|"
            WS-EQ-BANK(WS-IDX) DELIMITED BY SPACE "|"
            WS-AMT-STR DELIMITED BY SIZE
            INTO EFT-OUT
        END-STRING
        WRITE EFT-OUT
    END-PERFORM
    CLOSE EFT-FILE.

REWRITE-VERIFY-FILE.
    OPEN OUTPUT VERIFY-FILE
    MOVE "instruction_id|claim_id|event_id|bank_account|amount_cents|reason_code" TO VERIFY-OUT
    WRITE VERIFY-OUT
    PERFORM VARYING WS-IDX FROM 1 BY 1 UNTIL WS-IDX > WS-VER-COUNT
        MOVE WS-VQ-AMT(WS-IDX) TO WS-AMT-W
        PERFORM PREPARE-AMT-STR
        MOVE SPACES TO VERIFY-OUT
        STRING WS-VQ-INST(WS-IDX) DELIMITED BY SPACE "|"
            WS-VQ-CLAIM(WS-IDX) DELIMITED BY SPACE "|"
            WS-VQ-EVENT(WS-IDX) DELIMITED BY SPACE "|"
            WS-VQ-BANK(WS-IDX) DELIMITED BY SPACE "|"
            WS-AMT-STR DELIMITED BY SIZE "|"
            WS-VQ-CODE(WS-IDX) DELIMITED BY SPACE
            INTO VERIFY-OUT
        END-STRING
        WRITE VERIFY-OUT
    END-PERFORM
    CLOSE VERIFY-FILE.

REWRITE-LEDGER-FILE.
    OPEN OUTPUT OUT-LED-FILE
    MOVE "instruction_id|claim_id|event_id|rail|amount_cents|status" TO OUT-LED-LINE
    WRITE OUT-LED-LINE
    PERFORM VARYING WS-IDX FROM 1 BY 1 UNTIL WS-IDX > WS-LED-COUNT
        MOVE WS-LG-AMT(WS-IDX) TO WS-AMT-W
        PERFORM PREPARE-AMT-STR
        MOVE SPACES TO OUT-LED-LINE
        STRING WS-LG-INST(WS-IDX) DELIMITED BY SPACE "|"
            WS-LG-CLAIM(WS-IDX) DELIMITED BY SPACE "|"
            WS-LG-EVENT(WS-IDX) DELIMITED BY SPACE "|"
            WS-LG-RAIL(WS-IDX) DELIMITED BY SPACE "|"
            WS-AMT-STR DELIMITED BY SIZE "|"
            WS-LG-STAT(WS-IDX) DELIMITED BY SPACE
            INTO OUT-LED-LINE
        END-STRING
        WRITE OUT-LED-LINE
    END-PERFORM
    CLOSE OUT-LED-FILE.

COMPUTE-CONTROL-TOTALS.
    MOVE 0 TO WS-CTL-PQ-C WS-CTL-PQ-A WS-CTL-MR-C WS-CTL-MR-A
        WS-CTL-RJ-C WS-CTL-RJ-A WS-CTL-CQ-C WS-CTL-CQ-A
        WS-CTL-EQ-C WS-CTL-EQ-A WS-CTL-BV-C WS-CTL-BV-A
        WS-CTL-LG-C WS-CTL-LG-A
    IF WS-STAGE >= 4
        PERFORM VARYING WS-IDX FROM 1 BY 1 UNTIL WS-IDX > WS-LED-COUNT
            MOVE WS-LG-STAT(WS-IDX) TO WS-TRIM
            PERFORM NORM-TRIM-TO-NORM
            IF WS-NORM = "COMMITTED"
                ADD 1 TO WS-CTL-PQ-C
                ADD WS-LG-AMT(WS-IDX) TO WS-CTL-PQ-A
            END-IF
        END-PERFORM
    ELSE
        PERFORM VARYING WS-IDX FROM 1 BY 1 UNTIL WS-IDX > WS-DEC-COUNT
            IF WS-DC-DEC(WS-IDX) = "PAYMENT_QUEUED"
                ADD 1 TO WS-CTL-PQ-C
                ADD WS-DC-AMT(WS-IDX) TO WS-CTL-PQ-A
            END-IF
        END-PERFORM
    END-IF
    MOVE WS-REV-COUNT TO WS-CTL-MR-C
    PERFORM VARYING WS-IDX FROM 1 BY 1 UNTIL WS-IDX > WS-REV-COUNT
        ADD WS-RV-AMT(WS-IDX) TO WS-CTL-MR-A
    END-PERFORM
    PERFORM VARYING WS-IDX FROM 1 BY 1 UNTIL WS-IDX > WS-DEC-COUNT
        IF WS-DC-DEC(WS-IDX) = "REJECT"
            ADD WS-DC-AMT(WS-IDX) TO WS-CTL-RJ-A
        END-IF
    END-PERFORM
    MOVE WS-REJ-COUNT TO WS-CTL-RJ-C
    MOVE WS-CHK-COUNT TO WS-CTL-CQ-C
    PERFORM VARYING WS-IDX FROM 1 BY 1 UNTIL WS-IDX > WS-CHK-COUNT
        ADD WS-CQ-AMT(WS-IDX) TO WS-CTL-CQ-A
    END-PERFORM
    MOVE WS-EFT-COUNT TO WS-CTL-EQ-C
    PERFORM VARYING WS-IDX FROM 1 BY 1 UNTIL WS-IDX > WS-EFT-COUNT
        ADD WS-EQ-AMT(WS-IDX) TO WS-CTL-EQ-A
    END-PERFORM
    MOVE WS-VER-COUNT TO WS-CTL-BV-C
    PERFORM VARYING WS-IDX FROM 1 BY 1 UNTIL WS-IDX > WS-VER-COUNT
        ADD WS-VQ-AMT(WS-IDX) TO WS-CTL-BV-A
    END-PERFORM
    MOVE WS-LED-COUNT TO WS-CTL-LG-C
    PERFORM VARYING WS-IDX FROM 1 BY 1 UNTIL WS-IDX > WS-LED-COUNT
        ADD WS-LG-AMT(WS-IDX) TO WS-CTL-LG-A
    END-PERFORM.

REWRITE-CONTROL-FILE.
    OPEN OUTPUT CONTROL-FILE
    MOVE "metric|count|amount_cents" TO CONTROL-OUT
    WRITE CONTROL-OUT
    MOVE "payment_queued" TO WS-NORM
    MOVE WS-CTL-PQ-C TO WS-AMT-W
    MOVE WS-CTL-PQ-A TO WS-AMT
    PERFORM WRITE-ONE-CTL-ROW
    MOVE "manual_review" TO WS-NORM
    MOVE WS-CTL-MR-C TO WS-AMT-W
    MOVE WS-CTL-MR-A TO WS-AMT
    PERFORM WRITE-ONE-CTL-ROW
    MOVE "rejected" TO WS-NORM
    MOVE WS-CTL-RJ-C TO WS-AMT-W
    MOVE WS-CTL-RJ-A TO WS-AMT
    PERFORM WRITE-ONE-CTL-ROW
    MOVE "check_queue" TO WS-NORM
    MOVE WS-CTL-CQ-C TO WS-AMT-W
    MOVE WS-CTL-CQ-A TO WS-AMT
    PERFORM WRITE-ONE-CTL-ROW
    MOVE "eft_queue" TO WS-NORM
    MOVE WS-CTL-EQ-C TO WS-AMT-W
    MOVE WS-CTL-EQ-A TO WS-AMT
    PERFORM WRITE-ONE-CTL-ROW
    MOVE "bank_verify" TO WS-NORM
    MOVE WS-CTL-BV-C TO WS-AMT-W
    MOVE WS-CTL-BV-A TO WS-AMT
    PERFORM WRITE-ONE-CTL-ROW
    MOVE "committed_ledger" TO WS-NORM
    MOVE WS-CTL-LG-C TO WS-AMT-W
    MOVE WS-CTL-LG-A TO WS-AMT
    PERFORM WRITE-ONE-CTL-ROW
    CLOSE CONTROL-FILE.

WRITE-ONE-CTL-ROW.
    PERFORM PREPARE-CNT-STR
    MOVE WS-AMT TO WS-AMT-W
    PERFORM PREPARE-AMT-STR
    MOVE SPACES TO CONTROL-OUT
    STRING WS-NORM DELIMITED BY SPACE "|"
        WS-CNT-STR DELIMITED BY SPACE "|"
        WS-AMT-STR DELIMITED BY SPACE
        INTO CONTROL-OUT
    END-STRING
    WRITE CONTROL-OUT.

NORM-TRIM-TO-NORM.
    MOVE FUNCTION TRIM(WS-TRIM) TO WS-TRIM
    MOVE FUNCTION UPPER-CASE(WS-TRIM) TO WS-NORM.

PREPARE-AMT-STR.
    MOVE WS-AMT-W TO WS-DSP
    MOVE FUNCTION TRIM(WS-DSP LEADING) TO WS-AMT-STR
    IF WS-AMT-STR = SPACES MOVE "0" TO WS-AMT-STR END-IF.

PREPARE-CNT-STR.
    MOVE WS-AMT-W TO WS-CNT-DSP
    MOVE FUNCTION TRIM(WS-CNT-DSP LEADING) TO WS-CNT-STR
    IF WS-CNT-STR = SPACES MOVE "0" TO WS-CNT-STR END-IF.
