IDENTIFICATION DIVISION.
PROGRAM-ID. RETROPAY.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 INCIDENT-NOTE PIC X(72) VALUE
   "Retroactive payroll correction engine delegates to batch runtime".
PROCEDURE DIVISION.
    DISPLAY INCIDENT-NOTE
    GOBACK.
